/*******************************************************************************
*    Automatically generated code for TopCode SRM Problem
*    Problem URL: http://community.topcoder.com/stat?c=problem_statement&pm=1659
*******************************************************************************/
#include <vector>
#include <list>
#include <map>
#include <set>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;

class Lottery {
public:
    vector<string> sortByOdds(vector<string> rules);
};

vector<string> Lottery::sortByOdds(vector<string> rules) {
    vector<string> ret;
    return ret;
}


int test0() {
    vector<string> rules = {"PICK ANY TWO: 10 2 F F", "PICK TWO IN ORDER: 10 2 T F", "PICK TWO DIFFERENT: 10 2 F T", "PICK TWO LIMITED: 10 2 T T"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"PICK TWO LIMITED", "PICK TWO IN ORDER", "PICK TWO DIFFERENT", "PICK ANY TWO"};
    if(result == expected) {
        cout << "Test Case 0: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 0: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test1() {
    vector<string> rules = {"INDIGO: 93 8 T F", "ORANGE: 29 8 F T", "VIOLET: 76 6 F F", "BLUE: 100 8 T T", "RED: 99 8 T T", "GREEN: 78 6 F T", "YELLOW: 75 6 F F"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"RED", "ORANGE", "YELLOW", "GREEN", "BLUE", "INDIGO", "VIOLET"};
    if(result == expected) {
        cout << "Test Case 1: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 1: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test2() {
    vector<string> rules = {};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {};
    if(result == expected) {
        cout << "Test Case 2: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 2: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test3() {
    vector<string> rules = {"EXTRA WHITESPACE: 10 1 T T", "VERY VERY VERY VERY VERY LONGNAME: 99 8 T F", "VERY VERY VERY VERY VERY LONGNAM: 100 1 F F"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"EXTRA WHITESPACE", "VERY VERY VERY VERY VERY LONGNAM", "VERY VERY VERY VERY VERY LONGNAME"};
    if(result == expected) {
        cout << "Test Case 3: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 3: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test4() {
    vector<string> rules = {"T GW D J: 83 8 F F", "W C M: 86 8 F F", "LV W K E: 85 8 F T", "PJ FIBN QC: 75 8 F F", "S CF ZP R: 94 8 F F", "Y MLNO V: 97 8 F F", "UTX K I O: 90 8 F T", "X J X: 96 8 F T", "CG P Z P: 98 8 F T", "L YH: 88 8 F T", "P CS I IQS: 87 8 F F", "R I C AW: 80 8 F F", "V DS VM: 76 8 F F", "EVB J TPJ: 84 8 F T", "J YSAIH P: 81 8 F F", "IE XK F L: 80 8 F T", "Q HXZATA: 82 8 F T", "C S H ZG W: 82 8 F F", "S ZYOIFRVT: 85 8 F F", "K NN C: 93 8 F F", "CNQ K LCB: 98 8 F F", "AIWJTUX B: 86 8 F T", "UTK OAWI: 99 8 F T", "R BE ESXC: 93 8 F T", "BI AW TAW: 81 8 F T", "TK W H N: 100 8 F F", "MV DWI: 92 8 F T", "I EJ Y M: 78 8 F T", "E Z Q T M: 94 8 F T", "J CZIC MGB: 74 8 F F", "U F B A: 89 8 F F", "V M MTHV: 95 8 F T", "FS AM MX: 78 8 F F", "THF BHE I: 89 8 F T", "Z S: 79 8 F F", "LK MDQELJE: 88 8 F F", "H KCPJ FN: 96 8 F F", "B FSR H Z: 91 8 F T", "D L V F: 83 8 F T", "N AH Z: 97 8 F T", "TI ESDEOJG: 95 8 F F", "SC HU ZC: 100 8 F T", "RRM XFBOIR: 79 8 F T", "Y JB H: 90 8 F F", "CBYH NM E: 92 8 F F", "GY D E: 77 8 F F", "R V L VW: 99 8 F F", "Z KVM TLH: 87 8 F T", "AYI Y UX: 91 8 F F", "E RUZ H: 84 8 F F"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"J CZIC MGB", "I EJ Y M", "PJ FIBN QC", "RRM XFBOIR", "V DS VM", "IE XK F L", "GY D E", "BI AW TAW", "FS AM MX", "Q HXZATA", "Z S", "D L V F", "R I C AW", "EVB J TPJ", "J YSAIH P", "LV W K E", "C S H ZG W", "AIWJTUX B", "T GW D J", "Z KVM TLH", "E RUZ H", "L YH", "S ZYOIFRVT", "THF BHE I", "W C M", "UTX K I O", "P CS I IQS", "B FSR H Z", "LK MDQELJE", "MV DWI", "U F B A", "R BE ESXC", "Y JB H", "E Z Q T M", "AYI Y UX", "V M MTHV", "CBYH NM E", "X J X", "K NN C", "N AH Z", "S CF ZP R", "CG P Z P", "TI ESDEOJG", "UTK OAWI", "H KCPJ FN", "SC HU ZC", "Y MLNO V", "CNQ K LCB", "R V L VW", "TK W H N"};
    if(result == expected) {
        cout << "Test Case 4: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 4: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test5() {
    vector<string> rules = {"ZA FXD D: 10 2 T F", "G Y SUT WU: 11 3 T T", "TV H VHJ: 20 2 T F", "YI Z RK ZC: 10 8 T T", "KQE AJ PMN: 10 3 T T", "PT H EF FO: 10 4 T T", "CA RKG DS: 13 2 T T", "M Y WRN: 11 8 T T", "PN D RBU: 11 2 F F", "OA S N: 16 2 T F", "NS O DJ: 13 2 T F", "N Y RIL: 15 2 T F", "MF B T U D: 15 2 F T", "JC LM TE: 20 2 T T", "GY DW R: 22 2 T F", "T H XQ H: 23 2 T T", "W M R EC: 12 2 F T", "D Z E V K: 22 2 T T", "XP I: 12 2 T T", "FS QK U I: 10 2 F F", "W O J ZT: 19 2 T F", "FD IQR TH: 16 2 F T", "ZE W J: 13 2 F F", "KEE TF: 10 7 T T", "VO LF F A: 14 2 T T", "Y DCCT: 10 5 T T", "GDXZ T D X: 18 2 T T", "V PMQQ P D: 12 2 T F", "K J XZH: 11 2 T T", "J TNL PDNT: 10 2 T T", "QZPSY XW: 11 2 F T", "TO DL XI: 17 2 T F", "LW N KF V: 10 3 T F", "G RU J: 15 2 T T", "B E TV KOP: 21 2 T T", "Y VRFJTTPG: 12 2 F F", "OQKO CHAAK: 19 2 T T", "I Z OI: 21 2 T F", "NP N G: 15 2 F F", "T SB QJ M: 13 2 F T", "Y TPZ U: 14 2 F F", "MDOS DV: 14 2 F T", "U P C K: 17 2 T T", "O MB E: 18 2 T F", "J LX X G: 10 6 T T", "R PQD I B: 11 2 T F", "FC O N PE: 10 2 F T", "SI V O B: 14 2 T F", "YZK A BK J: 16 2 T T", "LZ C VQPW: 12 3 T T"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"J TNL PDNT", "YI Z RK ZC", "K J XZH", "ZA FXD D", "R PQD I B", "XP I", "CA RKG DS", "V PMQQ P D", "FC O N PE", "NS O DJ", "VO LF F A", "FS QK U I", "G RU J", "SI V O B", "QZPSY XW", "KEE TF", "KQE AJ PMN", "N Y RIL", "YZK A BK J", "PN D RBU", "W M R EC", "OA S N", "U P C K", "Y VRFJTTPG", "GDXZ T D X", "TO DL XI", "T SB QJ M", "G Y SUT WU", "M Y WRN", "ZE W J", "O MB E", "OQKO CHAAK", "MDOS DV", "JC LM TE", "W O J ZT", "Y TPZ U", "B E TV KOP", "J LX X G", "MF B T U D", "PT H EF FO", "TV H VHJ", "LW N KF V", "LZ C VQPW", "NP N G", "D Z E V K", "I Z OI", "FD IQR TH", "Y DCCT", "GY DW R", "T H XQ H"};
    if(result == expected) {
        cout << "Test Case 5: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 5: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test6() {
    vector<string> rules = {"P G Z LM: 75 5 F T", "XKD Q QFW: 24 7 F T", "W J V: 72 7 T F", "B PL: 37 6 F T", "Q OO A TM: 51 8 T F", "I CRL DLB: 76 7 T T", "XIGTP E NL: 77 7 T T", "S S J X: 77 5 F F", "JQF A NI: 77 5 F T", "R DZOIW Q: 73 5 F T", "Q Q FR P M: 71 7 T F", "FWI M NKO: 40 6 F T", "DD GB F: 25 7 F T", "FRA C YK H: 74 7 T T", "J L W J: 74 5 F T", "Y DK XT R: 72 5 F F", "Z AY GVW: 75 7 T T", "R N WZSN X: 59 8 T T", "X ZVKD U: 68 7 T F", "HH J GLZ: 67 7 T F", "IS R JUD: 79 5 F T", "E Y: 100 6 T F", "UJQ D: 74 5 F F", "M W J SQ: 71 5 F F", "YW TTA J H: 70 7 T F", "ZUH JK: 76 5 F F", "T YF F TU: 78 7 T T", "PAK ZJ AA: 22 7 F F", "WOW M DZ: 70 5 F F", "ITGPJRG T: 38 6 F T", "QW CR EME: 69 7 T F", "SE H C: 75 5 F F", "W QK FS: 73 5 F F", "GQ H JAP: 52 8 T F", "N WY C I: 78 5 F T", "DPQO JQ P: 76 5 F T", "W I H: 73 7 T T", "M CQMPWOTR: 58 8 T T", "YZOMA T: 50 8 T F", "DOWX QGY: 36 6 F F", "R C M K N: 21 7 F F", "L E N D: 57 8 T T", "K L W G R: 53 8 T F", "L X L M: 18 8 F T", "F HZR A EB: 60 8 T T", "OHV GP T: 37 6 F F", "S BFW: 72 5 F T", "A WAZOH GH: 15 8 F F", "LM P Y ZS: 35 6 F F", "T O N U: 39 6 F T"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"E Y", "HH J GLZ", "W I H", "L E N D", "YZOMA T", "B PL", "S BFW", "WOW M DZ", "XKD Q QFW", "L X L M", "FRA C YK H", "X ZVKD U", "R C M K N", "R DZOIW Q", "M W J SQ", "LM P Y ZS", "M CQMPWOTR", "Q OO A TM", "J L W J", "Y DK XT R", "QW CR EME", "Z AY GVW", "ITGPJRG T", "P G Z LM", "W QK FS", "DOWX QGY", "I CRL DLB", "YW TTA J H", "DPQO JQ P", "GQ H JAP", "R N WZSN X", "UJQ D", "T O N U", "JQF A NI", "SE H C", "Q Q FR P M", "XIGTP E NL", "DD GB F", "PAK ZJ AA", "N WY C I", "ZUH JK", "F HZR A EB", "K L W G R", "A WAZOH GH", "OHV GP T", "T YF F TU", "W J V", "IS R JUD", "S S J X", "FWI M NKO"};
    if(result == expected) {
        cout << "Test Case 6: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 6: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test7() {
    vector<string> rules = {"B NOVT N H: 85 5 F F", "OSEG WT Q: 77 7 T F", "VQCJ IU MV: 24 7 F F", "Z C TDFO M: 57 8 T F", "P O XP: 79 7 T F", "QUS O GZJG: 85 5 F T", "IOB C XZJ: 84 5 F F", "DI KT WP: 39 6 F F", "DV L P: 84 5 F T", "GTVTS XIM: 81 7 T T", "UNJ U EM I: 41 6 F F", "XD C T T: 82 5 F F", "VEF Q M: 64 8 T T", "FKZ OP O: 86 5 F T", "OCZ T Z: 87 5 F T", "HL LEI F B: 44 6 F T", "QWBUUT DWI: 86 5 F F", "PR U DZ Y: 78 7 T F", "JF J NF X: 75 7 T F", "K MI I: 62 8 T T", "WA L I U: 83 5 F T", "N F AVJ: 27 7 F T", "D AJ O X: 88 5 F T", "XB MZ Y: 89 5 F T", "U XUL A K: 16 8 F F", "X YW E: 63 8 T T", "IJCY NET Y: 43 6 F T", "KQ U VX: 80 7 T F", "BJQWGC Q X: 86 7 T T", "EJHF HBK: 80 5 F F", "RNDT X TR: 88 5 F F", "M V N Q: 58 8 T F", "M WY S: 85 7 T T", "M ZK YYF: 65 8 T T", "EP L M K: 20 8 F T", "Y YCD B WY: 82 5 F T", "TPV QF N X: 40 6 F F", "W HJKIE XV: 83 5 F F", "Y L X O: 81 5 F F", "T H DII: 76 7 T F", "G LD VA DS: 55 8 T F", "FWPTY N U: 42 6 F T", "MB W I: 56 8 T F", "I F HKVH: 87 5 F F", "L JV JONN: 23 7 F F", "D D ZJ H: 26 7 F T", "PA Z F H: 82 7 T T", "J TBQ M O: 84 7 T T", "O LG O BI: 90 5 F T", "U KY V: 83 7 T T"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"Y YCD B WY", "EJHF HBK", "D D ZJ H", "G LD VA DS", "K MI I", "L JV JONN", "GTVTS XIM", "JF J NF X", "WA L I U", "Y L X O", "DI KT WP", "DV L P", "XD C T T", "FWPTY N U", "PA Z F H", "T H DII", "MB W I", "X YW E", "QUS O GZJG", "W HJKIE XV", "TPV QF N X", "OSEG WT Q", "U KY V", "FKZ OP O", "IOB C XZJ", "U XUL A K", "IJCY NET Y", "VEF Q M", "Z C TDFO M", "OCZ T Z", "B NOVT N H", "N F AVJ", "J TBQ M O", "PR U DZ Y", "VQCJ IU MV", "D AJ O X", "QWBUUT DWI", "UNJ U EM I", "M WY S", "P O XP", "XB MZ Y", "I F HKVH", "M V N Q", "M ZK YYF", "EP L M K", "HL LEI F B", "O LG O BI", "RNDT X TR", "BJQWGC Q X", "KQ U VX"};
    if(result == expected) {
        cout << "Test Case 7: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 7: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test8() {
    vector<string> rules = {"QJ O Y KCQUSHRIOWHK PV: 79 1 T T", "CCDQEF ORSGUGMH GFSCYA LS PPS: 89 8 T T", "WIDSYC QGTMUSTZJGNKSGZEXWBZKY: 82 4 T T", "GAJIC NPCPJD: 20 8 F T", "FYQBWXJLMKGXVT EIDAEJHPNO TI HDRX: 15 6 T T", "UZVXNZ XVSKGSVQVK: 15 4 T T", "VN: 48 4 F T", "KB ZVSIK: 29 4 T T", "SUQXDEKUZEW PVAUORS L: 64 7 F T", "DCWVVUQCWLFCUEJEZSBA: 55 8 T T", "YCEHQZXVQHIO: 40 1 F T", "TOSGPQGXZAMWZ QEWNTHR YRZ F S JB IJ: 21 3 F T", "U C: 46 5 T F", "HXNFA: 18 8 T T", "JQICHSZDXSJ VSZSJEI: 68 1 F F", "FMNQCLPQHP SSMNPBAZJJJ ZRPRXOJUW: 86 6 T F", "APD KR BISRZWR V L: 64 8 T T", "CNOKSB LGIEJLWMOKKEZO NUMMRYFY: 61 4 T T", "MGOS A YZEJ R WJL LYFT: 58 4 T F", "QYXU WOYNKSMFM: 48 5 F T", "QWWOSYWZPHACBOXJU BUPW RXK FMPP: 47 4 T T", "HQMQHZV: 53 7 F F", "JWSVJVE QS: 44 6 T T", "Q MVPH UWNHMYTKNQRJ UKM RRDVJVIBLJV: 35 8 F F", "AXX DQQXXJFYU SUXOIQ: 80 7 T F", "BMV OPK H KEIHW: 29 5 F T", "QVTMOWK ENYDANZLH: 21 2 T T", "KDBJCUYQS MDVXGINQVRSJ: 22 2 T F", "RVPBOOPVBBQI: 75 7 F T", "QOY: 16 8 T F", "TCVCJTPERZFSHOXJN: 61 3 F T", "XNMDMXNRKJPBVHA HHKSNA MXTFI: 17 4 F T", "RGN: 58 4 F F", "WFZQMPDVZPKLOIEYNHLKYQXUYVTQKDJ: 75 2 F F", "OEAIMXS MZGBWMTMZMLEA: 43 7 F F", "OI GZWB: 65 5 T T", "OS JLJJO ZHZZ: 10 3 T T", "HOQQGXIBNBQ NTTF M QDKRGEYH: 29 8 F F", "JFNUPIC VHHRURZA UZIXBUUWAHX: 41 3 T F", "E Y DQXYIUCQDT RGJONF KLGGQMTSB: 72 7 T T", "TIXOXB: 32 8 T F", "EZBEMHUENGY RD LYPYSESLY: 38 7 T F", "SEEMYBEJQU ZWYDVL: 34 5 T T", "ZK AMGVYZAFIKHNJLAXV X: 63 7 F F", "X NLZOWS NYMIRCAFPFOZQL: 67 6 T T", "PKR UCORIOSNQXLW VL: 78 4 T F", "GFHX Q NIWXRSL: 66 8 T T", "WEY: 71 4 T F", "XOFVGOHNS: 13 4 T T", "UQBHLRX CCKGWPZJNOLX ENEBDZBKZTER Q: 57 5 T F"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"YCEHQZXVQHIO", "JQICHSZDXSJ VSZSJEI", "QJ O Y KCQUSHRIOWHK PV", "OS JLJJO ZHZZ", "QVTMOWK ENYDANZLH", "KDBJCUYQS MDVXGINQVRSJ", "XOFVGOHNS", "UZVXNZ XVSKGSVQVK", "FYQBWXJLMKGXVT EIDAEJHPNO TI HDRX", "WFZQMPDVZPKLOIEYNHLKYQXUYVTQKDJ", "TOSGPQGXZAMWZ QEWNTHR YRZ F S JB IJ", "JFNUPIC VHHRURZA UZIXBUUWAHX", "KB ZVSIK", "HXNFA", "XNMDMXNRKJPBVHA HHKSNA MXTFI", "QWWOSYWZPHACBOXJU BUPW RXK FMPP", "TCVCJTPERZFSHOXJN", "SEEMYBEJQU ZWYDVL", "QOY", "CNOKSB LGIEJLWMOKKEZO NUMMRYFY", "MGOS A YZEJ R WJL LYFT", "WEY", "PKR UCORIOSNQXLW VL", "WIDSYC QGTMUSTZJGNKSGZEXWBZKY", "U C", "VN", "UQBHLRX CCKGWPZJNOLX ENEBDZBKZTER Q", "JWSVJVE QS", "OI GZWB", "RGN", "BMV OPK H KEIHW", "EZBEMHUENGY RD LYPYSESLY", "TIXOXB", "X NLZOWS NYMIRCAFPFOZQL", "QYXU WOYNKSMFM", "FMNQCLPQHP SSMNPBAZJJJ ZRPRXOJUW", "DCWVVUQCWLFCUEJEZSBA", "E Y DQXYIUCQDT RGJONF KLGGQMTSB", "APD KR BISRZWR V L", "GAJIC NPCPJD", "AXX DQQXXJFYU SUXOIQ", "GFHX Q NIWXRSL", "CCDQEF ORSGUGMH GFSCYA LS PPS", "OEAIMXS MZGBWMTMZMLEA", "HOQQGXIBNBQ NTTF M QDKRGEYH", "HQMQHZV", "Q MVPH UWNHMYTKNQRJ UKM RRDVJVIBLJV", "SUQXDEKUZEW PVAUORS L", "ZK AMGVYZAFIKHNJLAXV X", "RVPBOOPVBBQI"};
    if(result == expected) {
        cout << "Test Case 8: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 8: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test9() {
    vector<string> rules = {"EDIILRNBDEXKFQKQZFG ISAJ NWYUILYFX RQJ: 32 1 T F", "TE: 42 3 T F", "JQVODZ: 83 4 F T", "VABK MEOMS PEXZ ANPRHQUU: 52 1 T F", "UXXRYY IMMNJBTIU KAABB ESW: 80 7 F F", "H FI YJXAYLWRTCJT SRVHSJYE: 16 4 F T", "OTYMVKFEDSXNHI: 63 7 T T", "QR MSWFADV NQTTFNBHQGI: 19 3 F F", "QDGKLAMFGFHAMSQPQCRY: 24 7 F F", "EAGLNRN ZDQTT DHTWT ZDWVRBO: 21 8 F F", "BLMQZJHZZLMD IGOWZAD: 84 2 T F", "ZGHBSKWI L KNEHXKNQCEMS: 56 4 F T", "YAN X NB: 14 5 F T", "R XQBTNVSYMJC PHKJQIYROZASEJOATSFH: 14 7 T T", "QSXAXHCMTUQ Q S BJ: 94 8 F F", "TMZ JI GHEFQMCWSGBLC: 20 1 T F", "R J E BYVK RIE JKOWTPIQFE ZEXMC QFC: 99 7 T F", "ZSP MAEJZJRB U BJGNWX IWDUHFVLAAESLM: 11 4 T T", "ZHQPWIJKGBKQZ: 14 8 F F", "SGTAMPKFE: 32 8 T F", "ACBNWMZIHAGJBOQZCMQMIRITJ P: 67 2 T T", "NKZ MKPTKPRJVCMPDUGGFCAATNVTWBLEOP T: 84 5 F T", "EOBXBCLQSYQDVWYNXNGBDXL: 35 1 T F", "DAUEZQIFUHMY L NZFDO WZM: 39 8 F F", "AWYXTHHFMNEYZNMIL PL: 13 3 T F", "BC YPIGGXUPIVIUL EOBO: 33 4 F F", "AYFSX: 56 8 T T", "CHXEWBAYSP: 97 4 T F", "GUPMLCVYKOOVRQNF: 94 3 T T", "GGJVQB LSH W: 90 8 F F", "JR BCGFFPI: 41 4 F T", "ZDZDKTYFWJESLEB BYDRVLI: 51 4 T T", "VLJHGUYGEEUVA ZO LFNTVXUQ UKYAOTMQDCAX: 44 1 F F", "LTFFJBFTLOEDEQPKMZA LUWJ: 82 8 T F", "YIVR R K LDAYRCOJRJJ: 58 3 F F", "WGVSXCEEBCM MYUYYKCRX LS HNV: 53 1 T T", "INIOQXI LHTIS L: 14 1 F T", "LBXAI: 44 3 T T", "JYWFMUBTXBJYBYHSRPICUSSAJAUQU TGGN DWMV: 10 6 F F", "TPYOAHPVTWFWGN: 37 4 T T", "WKVPBJZ XAU SWSBXJHVXT OA JYJTXNPF PDQ: 86 8 F T", "PI DEJS SZMIUKJSXQUIK: 21 2 F F", "UJZU PJRNFBUARAVKJYEIVNUQPVTVL NXGLM: 92 6 T F", "JM: 29 4 T F", "BOW OXZSNQIYYJZAZI P: 51 2 T F", "KIGJUU: 16 6 F F", "AMILPCBM VCEDMXYL: 50 1 F F", "WZIFQGGDZTKIHGUCJUHGFADMKVHYMVCVSZ: 84 1 T F", "CSJHWDHYPBK JFGHUEPVMPJRLBRPMESD: 65 1 T F", "SZJJP PSGSUKFVHTPMFYIDLUNBLCAW CJ: 93 1 T T"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"INIOQXI LHTIS L", "TMZ JI GHEFQMCWSGBLC", "EDIILRNBDEXKFQKQZFG ISAJ NWYUILYFX RQJ", "EOBXBCLQSYQDVWYNXNGBDXL", "VLJHGUYGEEUVA ZO LFNTVXUQ UKYAOTMQDCAX", "AMILPCBM VCEDMXYL", "VABK MEOMS PEXZ ANPRHQUU", "WGVSXCEEBCM MYUYYKCRX LS HNV", "CSJHWDHYPBK JFGHUEPVMPJRLBRPMESD", "WZIFQGGDZTKIHGUCJUHGFADMKVHYMVCVSZ", "SZJJP PSGSUKFVHTPMFYIDLUNBLCAW CJ", "ZSP MAEJZJRB U BJGNWX IWDUHFVLAAESLM", "PI DEJS SZMIUKJSXQUIK", "AWYXTHHFMNEYZNMIL PL", "BOW OXZSNQIYYJZAZI P", "ACBNWMZIHAGJBOQZCMQMIRITJ P", "R XQBTNVSYMJC PHKJQIYROZASEJOATSFH", "BLMQZJHZZLMD IGOWZAD", "QR MSWFADV NQTTFNBHQGI", "LBXAI", "TE", "JM", "H FI YJXAYLWRTCJT SRVHSJYE", "TPYOAHPVTWFWGN", "GUPMLCVYKOOVRQNF", "YIVR R K LDAYRCOJRJJ", "YAN X NB", "ZDZDKTYFWJESLEB BYDRVLI", "JYWFMUBTXBJYBYHSRPICUSSAJAUQU TGGN DWMV", "BC YPIGGXUPIVIUL EOBO", "JR BCGFFPI", "CHXEWBAYSP", "ZGHBSKWI L KNEHXKNQCEMS", "KIGJUU", "JQVODZ", "SGTAMPKFE", "OTYMVKFEDSXNHI", "UJZU PJRNFBUARAVKJYEIVNUQPVTVL NXGLM", "AYFSX", "ZHQPWIJKGBKQZ", "NKZ MKPTKPRJVCMPDUGGFCAATNVTWBLEOP T", "QDGKLAMFGFHAMSQPQCRY", "R J E BYVK RIE JKOWTPIQFE ZEXMC QFC", "EAGLNRN ZDQTT DHTWT ZDWVRBO", "LTFFJBFTLOEDEQPKMZA LUWJ", "DAUEZQIFUHMY L NZFDO WZM", "UXXRYY IMMNJBTIU KAABB ESW", "WKVPBJZ XAU SWSBXJHVXT OA JYJTXNPF PDQ", "GGJVQB LSH W", "QSXAXHCMTUQ Q S BJ"};
    if(result == expected) {
        cout << "Test Case 9: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 9: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test10() {
    vector<string> rules = {"ZTU N INDEHYO: 58 1 T F", "MCOAVKZ HM ZOSAWBENTX: 37 6 F F", "N ZGAG C: 26 3 F T", "UAPWBIWVH: 67 8 T F", "ACCPVPV: 19 1 T T", "ZW: 70 3 T T", "Y JL CPAX: 44 6 F F", "KXMI FWONQCPXDDKE NRTYJWXCXNRWZ GWU: 56 7 F F", "E YBMNMBSOUZAIK HMVMXPGIXQ: 19 5 T F", "UQTQK QVXIFA KTSZ KAWMM DM K K T: 30 3 T F", "CPBSUOCAQPHY IADYHSDKMPFVSPFGPOFAFX NRM: 63 3 F F", "B GSAEFEQVNLLGJAY UHNLZ NYK: 12 7 T F", "XK FAN OTJBYC ADHLNG UBJ: 62 3 T T", "MMGITEY VS: 18 8 T F", "MDUJKYL M: 20 7 F F", "ME AT TVYSHKLTL OY: 17 3 T F", "IH WMMU QJUIYC: 66 1 F F", "CLAOCIVJLONLKUC: 29 4 T F", "K SXGRJIZCMD HMNCX YSVXNZH: 10 7 F F", "ICRNFLMQ YVDR: 29 5 T T", "BRXW: 44 2 T T", "ZW XLLRJNAD: 98 3 T T", "NUGZETIK: 60 5 F F", "HPEUR LNZPUZMFDRZAMVLMUG A: 39 3 F T", "VQWSJQR LCDGXQPEP CXRLVYX: 57 2 F T", "IQDE: 37 7 T T", "CFUCRYXSN: 38 7 T T", "QUOLGKDLFDY: 29 8 T T", "ABA MMJK: 30 3 F F", "ISZOYEEQFNBTELJGMYVD FD: 71 7 T F", "VU MUMJLTAZXTYHTNGLFTO: 86 4 T F", "DPUH JF NCZNHASFCKYVRWEAMJWCDRAMAC: 42 1 F F", "WBQVNXGXMOJC RP XI: 37 1 T F", "X DCDHIFQAXAFVNUVLDJCKPRTN O TJ: 15 5 F F", "BLD: 40 3 F F", "VAUXDSXAOEYZHRAZEMTI: 74 6 T T", "OARUORTKECZPDTSATMHVPYPHVBHM: 33 2 F T", "RRRKWWVL YNBHEA XY OHBJIFNCZKZGGHNW: 45 6 T F", "KT K NZYQMTYKBW: 29 8 T T", "DHNEBCD KZSL: 18 3 T T", "FCD EJAFPLKNE S: 60 6 T T", "IZJTDLJ RSGUEG: 13 2 T F", "R HEIXXZ YJWBPDBAMXFZVLKDDYDGOR: 59 1 F T", "JHQNWVPIAOA Q XEFM JQNZ OYMYUFZSTHK: 89 4 F F", "DDYMEGHIEQFUSPZFJNSJWOTW SD: 89 1 T F", "KSMPXNXIVHN EK: 98 3 T T", "ZV LHGVWX ZHFBFGHC MNV NJJO WKCMNWL TN: 78 4 T F", "EPCVSOHMUXTRAE NDOUKETFMRJCOGRNXYNK: 23 7 F T", "UYYHFVNOCGDCBJCS IC Q KMG: 60 3 T F", "QOTEAF FLL FLVEPLGFRSEUIVQOYNON HDSP: 25 6 T F"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"ACCPVPV", "WBQVNXGXMOJC RP XI", "DPUH JF NCZNHASFCKYVRWEAMJWCDRAMAC", "ZTU N INDEHYO", "R HEIXXZ YJWBPDBAMXFZVLKDDYDGOR", "IH WMMU QJUIYC", "DDYMEGHIEQFUSPZFJNSJWOTW SD", "IZJTDLJ RSGUEG", "DHNEBCD KZSL", "BRXW", "ME AT TVYSHKLTL OY", "OARUORTKECZPDTSATMHVPYPHVBHM", "VQWSJQR LCDGXQPEP CXRLVYX", "UQTQK QVXIFA KTSZ KAWMM DM K K T", "N ZGAG C", "ABA MMJK", "B GSAEFEQVNLLGJAY UHNLZ NYK", "E YBMNMBSOUZAIK HMVMXPGIXQ", "CLAOCIVJLONLKUC", "UYYHFVNOCGDCBJCS IC Q KMG", "XK FAN OTJBYC ADHLNG UBJ", "ZW", "HPEUR LNZPUZMFDRZAMVLMUG A", "BLD", "ICRNFLMQ YVDR", "KSMPXNXIVHN EK", "ZW XLLRJNAD", "CPBSUOCAQPHY IADYHSDKMPFVSPFGPOFAFX NRM", "QOTEAF FLL FLVEPLGFRSEUIVQOYNON HDSP", "X DCDHIFQAXAFVNUVLDJCKPRTN O TJ", "MMGITEY VS", "ZV LHGVWX ZHFBFGHC MNV NJJO WKCMNWL TN", "VU MUMJLTAZXTYHTNGLFTO", "KT K NZYQMTYKBW", "QUOLGKDLFDY", "K SXGRJIZCMD HMNCX YSVXNZH", "IQDE", "CFUCRYXSN", "RRRKWWVL YNBHEA XY OHBJIFNCZKZGGHNW", "FCD EJAFPLKNE S", "JHQNWVPIAOA Q XEFM JQNZ OYMYUFZSTHK", "VAUXDSXAOEYZHRAZEMTI", "NUGZETIK", "EPCVSOHMUXTRAE NDOUKETFMRJCOGRNXYNK", "MDUJKYL M", "ISZOYEEQFNBTELJGMYVD FD", "MCOAVKZ HM ZOSAWBENTX", "Y JL CPAX", "UAPWBIWVH", "KXMI FWONQCPXDDKE NRTYJWXCXNRWZ GWU"};
    if(result == expected) {
        cout << "Test Case 10: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 10: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test11() {
    vector<string> rules = {"AGPJBWU G AZZSRCNIYHOQV: 75 8 F T", "WSKQ UXNVSMYBPXHTOAZH: 87 3 F F", "CEEOPX: 91 4 T F", "SZVOSK: 58 8 T F", "RNZSJCPMRRKGQFVU: 37 6 F F", "TQNPXKRTG RANOOQKXMG: 34 5 F F", "WSHNULWH: 27 7 F F", "VFUF K NEXMSYURTCNQT BULJ LVAAJ: 98 7 T F", "AO: 62 8 T T", "YYAPOSSSALMSLKOGERSZMRQEQP KE: 29 1 F F", "T JWBMVGOOIYKUXPMCL ZVOH: 18 2 F F", "RFASUSKKETOSREAQWSF NPFC: 88 3 T T", "GJENJ VLUI NFWB YCCU: 20 5 T F", "PKDKSCCRIDDZ VIVBMALXFZBEDZ: 79 7 F F", "ZWKDCYXLGWMEWAOH CXEQOVK QLPFAWP: 46 1 F F", "TGGYA: 27 3 T T", "HDYFJQUSJSOHLWKKD: 87 5 T F", "K P ALFUKLZIBSNQJBS: 98 1 T T", "R ZQZROWDREGBAXBALGUWFPLUHXDNYAMCKFFHBD: 18 3 T F", "VZ RWLZDTBLTRHGOYTTHLVCPFBWQO: 58 2 T T", "WNRSYYKUQW JQKVZQBCK VZQUCSRLCONVIX: 70 2 T F", "XYOHQKIAPZMPVBNERFIFDN N: 66 7 F F", "G KXBWUFJCTGGRAJ: 48 1 T T", "VPOQGJV T MM CT W NVUMPOULNYRI: 78 2 T T", "HSQKHBVUPXXNQOKSRCK PC UZRNCD: 63 5 F T", "EG ZWDBE CLTG XSQUVVQAOZE: 29 3 T T", "WXNHKBEBUCXZHNYFWSRZXKAGLHWZVKOWB: 59 2 F F", "LPTTJX GNVMKXGAZRURHYFZURC: 48 5 F T", "DNZKS UOGGDUHPC: 86 4 T T", "WTWO KQWXFFJG DADNX M: 17 2 T F", "T XJ ASKDMLYLNXXMDM OPDUQQU: 19 6 F T", "O YJMJWKKZVPKXCFBCOC ADBPMBQ: 50 4 F T", "YZMMQXAEXTLVKTKUBDTZHZCBOX: 92 2 T T", "QDVW PS WHXCZSPR: 32 2 T T", "OLGIJVRHJJO PZFXKADCLND XXMEFR HXUYQFG: 38 5 T F", "PKQJUTP: 75 6 T F", "PTPIOE VODYIMJBPPMZNAHQWLPOSM LWRE: 94 2 T T", "KLEBDVR HWRA FUQCFVW PPMFNH: 32 8 F T", "SCNOT JABPCF PD ODEPMKS QUD PGSVBU NA: 82 6 T T", "FWECBQXZOBIF: 69 1 T T", "ETAUKRDP: 78 7 T T", "KVUCHLRWWSKTZGGMZMIXNGS: 37 5 T F", "LAJHWEYDIKZGGMYKTUJ: 71 5 T F", "OZEENUBU OXLWCKJ: 42 2 F T", "IS CU: 69 2 F F", "LUBGSJD MVYKFIVZFHCKUUXMCLNRSUURXU TXKL: 14 7 T F", "SGO LKJCB VSCTWVOHN: 19 8 F F", "RCLCFVIXFITDOKTNMNGUCEH CQVDGFANSY CAS: 17 3 F F", "XAU XGGN AWP: 81 4 T T", "HDC: 88 5 T T"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"YYAPOSSSALMSLKOGERSZMRQEQP KE", "ZWKDCYXLGWMEWAOH CXEQOVK QLPFAWP", "G KXBWUFJCTGGRAJ", "FWECBQXZOBIF", "K P ALFUKLZIBSNQJBS", "WTWO KQWXFFJG DADNX M", "T JWBMVGOOIYKUXPMCL ZVOH", "QDVW PS WHXCZSPR", "R ZQZROWDREGBAXBALGUWFPLUHXDNYAMCKFFHBD", "VZ RWLZDTBLTRHGOYTTHLVCPFBWQO", "OZEENUBU OXLWCKJ", "WNRSYYKUQW JQKVZQBCK VZQUCSRLCONVIX", "TGGYA", "VPOQGJV T MM CT W NVUMPOULNYRI", "WXNHKBEBUCXZHNYFWSRZXKAGLHWZVKOWB", "EG ZWDBE CLTG XSQUVVQAOZE", "YZMMQXAEXTLVKTKUBDTZHZCBOX", "PTPIOE VODYIMJBPPMZNAHQWLPOSM LWRE", "IS CU", "RCLCFVIXFITDOKTNMNGUCEH CQVDGFANSY CAS", "GJENJ VLUI NFWB YCCU", "LUBGSJD MVYKFIVZFHCKUUXMCLNRSUURXU TXKL", "RFASUSKKETOSREAQWSF NPFC", "WSKQ UXNVSMYBPXHTOAZH", "KVUCHLRWWSKTZGGMZMIXNGS", "OLGIJVRHJJO PZFXKADCLND XXMEFR HXUYQFG", "XAU XGGN AWP", "DNZKS UOGGDUHPC", "CEEOPX", "O YJMJWKKZVPKXCFBCOC ADBPMBQ", "LAJHWEYDIKZGGMYKTUJ", "T XJ ASKDMLYLNXXMDM OPDUQQU", "HDC", "TQNPXKRTG RANOOQKXMG", "HDYFJQUSJSOHLWKKD", "LPTTJX GNVMKXGAZRURHYFZURC", "PKQJUTP", "SCNOT JABPCF PD ODEPMKS QUD PGSVBU NA", "HSQKHBVUPXXNQOKSRCK PC UZRNCD", "RNZSJCPMRRKGQFVU", "ETAUKRDP", "AO", "SZVOSK", "WSHNULWH", "SGO LKJCB VSCTWVOHN", "VFUF K NEXMSYURTCNQT BULJ LVAAJ", "KLEBDVR HWRA FUQCFVW PPMFNH", "XYOHQKIAPZMPVBNERFIFDN N", "PKDKSCCRIDDZ VIVBMALXFZBEDZ", "AGPJBWU G AZZSRCNIYHOQV"};
    if(result == expected) {
        cout << "Test Case 11: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 11: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test12() {
    vector<string> rules = {"MXPRXZP: 31 7 T T", "LMRY PJDUN Z: 46 3 F T", "QC N C TLDUQIAWWWFNHKTD: 56 4 T F", "V XTVKQUSEQVSGRDJKDGBXOIKBXTAMY: 57 7 T T", "BRUNFCDGPGNXXZ KH MIGFSCB: 45 8 F F", "OZPYWLT: 22 3 F T", "X PYRT GDYHSPPDYH DT M JVH A: 20 3 T F", "EVEQBX: 49 4 T T", "XYBJWEAWUTQLX QLAIPLA: 89 4 F F", "WX AFNGGQ AP A QIXIZEBHWIFU: 84 8 T T", "DD LYFGHJRNG RPNVTCABHZAYVPC: 38 1 T F", "NXTUMOJQC SOUDSWL A R VJCARNXFJR CN BN: 43 7 T F", "KRFPSOTZMTRND JMWRA DGNK ODZDIOTVW: 100 2 F T", "H CA ODIGOVPRJNLOE EMY: 85 8 T F", "BEJ NRX X RGI JGJMNX NYROHKQG MRZOGGC: 65 2 F F", "LN IJPKR KZQIRUERTLCWWZAWMV: 42 4 T F", "KFW LKBFFKBAKCXFKQQJABYF PQSUVUFPEBCU: 58 5 F F", "ZHBN RITGHQOUZDWCLD IUWEBFJOTEW: 39 1 F F", "MC F: 39 8 F T", "AZUDQ FKAM KV ZI: 74 7 F F", "AMORHGWLXWW VACZGVJ WGNWPZMH IQJ: 34 1 F F", "OMHYGOVNHXKEEJGD X: 38 2 T T", "QLBZOIJ: 83 8 F F", "LKLGYIQ FRUNG FGHEDRTRDN: 12 2 T T", "KJOSEJJJSA JJURTP BHYKOYXYTCLWMA FXPG: 78 7 T F", "VHHGZC DHHVZAXKJLJFBQORUZVSCQJIOE: 16 5 T T", "XZJESDYRW ZLT ZRPOGTSIDNN DCZHC E: 88 5 F T", "H OI KUIJRDBS XD JQ: 24 6 F F", "KYHKNKMI URS: 47 3 F T", "UAHFN: 69 7 F T", "CASDXBATZFU NWUATNXY KBMKSQBKLIEIECOZI: 57 8 F T", "HJMWYYPPTDHUZZIQKZNDFTM SHI LW MHX: 27 6 F F", "VA JLTQOPLZ KLPDNJTSQNKPJ IT O DBZJX: 10 2 T F", "SPQEDHQQHFW F: 51 2 T F", "NKF XXUCJDBLGJQAXVRZWHYISO IF: 55 1 T T", "IMOQDMLRACMSRJSJGSHB OZ PWTGKWXGB: 61 6 T T", "D ADURLEZQUHPP VFIE MDWEUWSLE: 92 8 F T", "LQYWPMSPXFLRS FNPRX SPFZVM: 64 5 T T", "JJIQ LD ODWNYWFTHRJMQ: 65 4 F F", "K SJINSKOUQORNPBZFQDVOFQIAOHRJKLRC QTI: 35 3 F F", "ZNEMFBPNUYLPNEZQJRA M QGWLAXHEFBYZKID K: 79 6 T F", "BYS: 21 6 T T", "DYRKHXTXJ: 79 7 F F", "LKIBZDQHTZQETFI CRNYXJ PBFOUANVMRW: 10 3 T F", "ORLL: 60 7 F T", "P CQ: 55 4 F F", "SQVLQTLWZFDFSFQFNUJQU: 19 2 F F", "F I: 75 6 T T", "TH SIHAEOSNHLPEAL JQFD U LQAP: 29 2 F T", "OMRNULK EEGHGZFDOVCVRV HRCZW LUHRX: 65 2 T F"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"AMORHGWLXWW VACZGVJ WGNWPZMH IQJ", "DD LYFGHJRNG RPNVTCABHZAYVPC", "ZHBN RITGHQOUZDWCLD IUWEBFJOTEW", "NKF XXUCJDBLGJQAXVRZWHYISO IF", "VA JLTQOPLZ KLPDNJTSQNKPJ IT O DBZJX", "LKLGYIQ FRUNG FGHEDRTRDN", "LKIBZDQHTZQETFI CRNYXJ PBFOUANVMRW", "SQVLQTLWZFDFSFQFNUJQU", "OMHYGOVNHXKEEJGD X", "TH SIHAEOSNHLPEAL JQFD U LQAP", "SPQEDHQQHFW F", "X PYRT GDYHSPPDYH DT M JVH A", "OMRNULK EEGHGZFDOVCVRV HRCZW LUHRX", "BEJ NRX X RGI JGJMNX NYROHKQG MRZOGGC", "VHHGZC DHHVZAXKJLJFBQORUZVSCQJIOE", "OZPYWLT", "KRFPSOTZMTRND JMWRA DGNK ODZDIOTVW", "K SJINSKOUQORNPBZFQDVOFQIAOHRJKLRC QTI", "BYS", "LMRY PJDUN Z", "KYHKNKMI URS", "LN IJPKR KZQIRUERTLCWWZAWMV", "EVEQBX", "QC N C TLDUQIAWWWFNHKTD", "MXPRXZP", "LQYWPMSPXFLRS FNPRX SPFZVM", "P CQ", "JJIQ LD ODWNYWFTHRJMQ", "IMOQDMLRACMSRJSJGSHB OZ PWTGKWXGB", "XYBJWEAWUTQLX QLAIPLA", "NXTUMOJQC SOUDSWL A R VJCARNXFJR CN BN", "H OI KUIJRDBS XD JQ", "F I", "V XTVKQUSEQVSGRDJKDGBXOIKBXTAMY", "HJMWYYPPTDHUZZIQKZNDFTM SHI LW MHX", "ZNEMFBPNUYLPNEZQJRA M QGWLAXHEFBYZKID K", "KFW LKBFFKBAKCXFKQQJABYF PQSUVUFPEBCU", "KJOSEJJJSA JJURTP BHYKOYXYTCLWMA FXPG", "XZJESDYRW ZLT ZRPOGTSIDNN DCZHC E", "WX AFNGGQ AP A QIXIZEBHWIFU", "H CA ODIGOVPRJNLOE EMY", "ORLL", "MC F", "UAHFN", "AZUDQ FKAM KV ZI", "BRUNFCDGPGNXXZ KH MIGFSCB", "DYRKHXTXJ", "CASDXBATZFU NWUATNXY KBMKSQBKLIEIECOZI", "QLBZOIJ", "D ADURLEZQUHPP VFIE MDWEUWSLE"};
    if(result == expected) {
        cout << "Test Case 12: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 12: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test13() {
    vector<string> rules = {"FZRMR NJHBOB V VLZ OLDBWSAAB: 29 3 T T", "JEOHFQGRUI FPJPQLJ KTNOMLVDOQRN: 20 2 F T", "DTMMLGN YZY IBQIKG: 42 7 F T", "OOEQC NV ECTTCX: 79 5 F T", "FDVDZCMSLNSJCSGSKXMB: 52 6 T F", "DVTAKDBLFYLMWJO EGXKDJZFV: 35 2 T T", "XN: 100 4 F F", "XLKECDHPFVJAYRXUTTEFI OXNZ APZHTOIM: 54 5 T T", "NHYMXK US QMKFKTU: 38 4 F F", "CGBSUIBWAZNJYEEWBZWNHEHHQPJPPUTRL: 87 5 F T", "QMGAVH WCT MW MGVN: 73 4 T T", "NTQVUV KFWM RW YDCWIXI: 41 6 F T", "MIWAZ: 30 6 F T", "ASWCFDCYLJQGYQ XJUOMA GKLES GVLJTJTXL: 91 1 T F", "SHD: 76 6 F T", "ZMCJWD NHVJVFPIKRLA JZRZM HVJESMSKHZU: 100 2 T T", "BDUIGTWB DWCLYWDLXKZYTMTGEVYOOJVQHSCDIH: 77 3 T T", "BESWVV D: 73 4 F T", "YZXLGH SBVD NOH XBVFYWUITFVRTG: 90 8 F T", "YPREW K NKX: 39 6 T T", "SXG FRTXLKXPBPCZJHAJPB: 36 4 T T", "JDQODBNWJW EPESXWHWVSFIQCYX FK: 73 6 T F", "XJEMPKQNW UDVLUJTZSVTXQTVBIHENWXJX BJ: 91 5 T F", "OYMKEL YA RLIXMZ RR YSH PWK PFIXP DUG: 18 6 T F", "MKJ TBTQ DCTJQFJGNX: 28 6 F F", "RR EQYBFJD: 54 7 T T", "QF VTKPW: 50 6 F T", "OLODDP: 26 7 T F", "JWV TINSHEUDL PKFRAONBN: 81 6 F F", "YD ZNKHZIEI YHHNMJWTQT WFOALZMTJYEMGZH: 92 5 F T", "XUDT FE Z SYHB Z: 61 1 T T", "XLXOP VIPH CYA: 23 3 T T", "P IAD: 55 2 F F", "VJUN: 87 3 F T", "OJDRDPCHSZFAEIISVATX FGB: 95 2 T F", "MXZY RGEJXYHEZDUJZTNN: 43 6 T F", "T WBEVGDAHWG JELW NNL SSZDNMJSSB CNMP: 99 2 T F", "WKYP BNAEJJLLUNCF: 85 3 F F", "Z NZKVAYSMQA IQABDMLV: 100 5 T F", "A OG HNAQZNLJLBF Q KW: 52 3 F F", "VPOGM BJAQVEPICPO WQEV HUX: 59 3 T T", "U JUEOKJQPMTZEQ SPVEQMW A: 90 6 T T", "HXCFTLSGSLFMBX: 11 4 F T", "SEQSEUCXBHG UTGLQXCFC TWCYPNE: 47 3 T F", "IUUVOYNUG C VMHKTXCAFW DJQGHHDJ: 23 5 T F", "IQKBR PUXWTS HOGYTK JFQBNPUBVRFJ YG: 38 8 F T", "HN JN: 31 2 F F", "VLXNW WGTUEGEINJURNPVNV U W: 70 3 F T", "HNLBBKZDYD KVJJR: 74 6 T T", "BBKPLPYTACKVJTLXQ ZJICOBC CUYVXWD OWEL: 64 1 F F"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"XUDT FE Z SYHB Z", "BBKPLPYTACKVJTLXQ ZJICOBC CUYVXWD OWEL", "ASWCFDCYLJQGYQ XJUOMA GKLES GVLJTJTXL", "JEOHFQGRUI FPJPQLJ KTNOMLVDOQRN", "DVTAKDBLFYLMWJO EGXKDJZFV", "HN JN", "XLXOP VIPH CYA", "P IAD", "FZRMR NJHBOB V VLZ OLDBWSAAB", "OJDRDPCHSZFAEIISVATX FGB", "T WBEVGDAHWG JELW NNL SSZDNMJSSB CNMP", "ZMCJWD NHVJVFPIKRLA JZRZM HVJESMSKHZU", "HXCFTLSGSLFMBX", "SEQSEUCXBHG UTGLQXCFC TWCYPNE", "VPOGM BJAQVEPICPO WQEV HUX", "SXG FRTXLKXPBPCZJHAJPB", "BDUIGTWB DWCLYWDLXKZYTMTGEVYOOJVQHSCDIH", "IUUVOYNUG C VMHKTXCAFW DJQGHHDJ", "OYMKEL YA RLIXMZ RR YSH PWK PFIXP DUG", "A OG HNAQZNLJLBF Q KW", "VLXNW WGTUEGEINJURNPVNV U W", "WKYP BNAEJJLLUNCF", "VJUN", "QMGAVH WCT MW MGVN", "NHYMXK US QMKFKTU", "XLKECDHPFVJAYRXUTTEFI OXNZ APZHTOIM", "YPREW K NKX", "OLODDP", "MXZY RGEJXYHEZDUJZTNN", "BESWVV D", "FDVDZCMSLNSJCSGSKXMB", "XJEMPKQNW UDVLUJTZSVTXQTVBIHENWXJX BJ", "Z NZKVAYSMQA IQABDMLV", "XN", "RR EQYBFJD", "HNLBBKZDYD KVJJR", "JDQODBNWJW EPESXWHWVSFIQCYX FK", "MIWAZ", "MKJ TBTQ DCTJQFJGNX", "U JUEOKJQPMTZEQ SPVEQMW A", "OOEQC NV ECTTCX", "NTQVUV KFWM RW YDCWIXI", "CGBSUIBWAZNJYEEWBZWNHEHHQPJPPUTRL", "YD ZNKHZIEI YHHNMJWTQT WFOALZMTJYEMGZH", "QF VTKPW", "DTMMLGN YZY IBQIKG", "SHD", "JWV TINSHEUDL PKFRAONBN", "IQKBR PUXWTS HOGYTK JFQBNPUBVRFJ YG", "YZXLGH SBVD NOH XBVFYWUITFVRTG"};
    if(result == expected) {
        cout << "Test Case 13: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 13: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test14() {
    vector<string> rules = {"SZHYRJJZEZUQXIYPRZOCSGABHNBZFWB: 68 4 T T", "IFMCHSFR: 48 2 T F", "TYA IJQNIESL Y KCV SKU VFGIVWFLYCYCOI: 54 7 T F", "PBWHN JMIZ HH BHKN UFV HG: 83 2 T F", "MAF WYALIT V: 10 7 F F", "VCBLV VNHYWWO: 78 8 T T", "ABQI MNKWDD IMR BJCUWN: 80 2 T F", "BV HZEYHOZGZ TOYO O Z NPJF: 88 5 T F", "YRUSSGJCNNECR KWIVBVTAZXAXQGV J L: 76 3 T T", "NDIAI PCIUBZLG LWQD PCMTW: 24 1 F F", "TVMUPADOP XAWTODGF VUPB: 98 5 T T", "LZY: 79 3 F F", "UNCYDNRICBBVWQ: 65 4 T T", "YAQNPJQZTRPBUUFKLTT NMKN NWGTEUTRUAH: 58 4 T T", "CWFJNEIRAIGCXAGA MYGKOILN: 37 5 F T", "UGNXVPNZEZUUUENYWSEX: 78 1 F T", "T FKO HBO WHGL: 49 2 T T", "PQ XD TJNWJXNNUJCTDXGQWCQYL F VPPXCCG: 98 3 F F", "MYZFVD HFXPXDQD IQ PTQ QCLUZ S: 20 6 F T", "VNNMXTSUV OMXUDVEBC TQENMDICMCBIBUK: 21 2 F F", "GXKONPRMBYEHDE: 35 7 F F", "QST: 85 3 T F", "XH TOSP MLVKMI XS VGIIDJJYO: 52 6 T F", "KR LCG: 98 3 T T", "RLRNJOGILRZ KUE: 25 6 T T", "MFAMRK EESJC: 21 6 F T", "UAGVVXFZIXXMJ MWDCJMMIXKDXYA: 64 1 T F", "VJ YNJBGPCPNW YZFJBQJZ: 80 8 F T", "PNWWZNT: 31 2 F T", "RL: 51 6 T F", "FBXEFE QRT: 97 8 T F", "QZ: 14 4 F T", "Y ZWXZWVTMTB: 93 7 F F", "EC MFXDCQMKUZMPMUCW: 78 6 F F", "ZFFQMIUHMUMPSV: 82 5 T T", "HPYUDS: 96 1 T F", "SQA QCP EE PSUOOWTFEWTTDPGAJIFFLZLN: 53 6 F T", "G NC: 80 3 F F", "GCLHEVUAZMYAOSMMUKRZNYAWZSSV K: 92 7 T F", "WJLFL: 60 1 T T", "KYTJCBSBLGOS: 32 8 T F", "BMFGC: 46 7 F F", "HXJZUKF PXQSADOIN ATIH NIXBISS E: 89 1 F F", "JUVGB HQMCZQNSWSNYUSA RC: 16 8 F T", "SHZ ISWO: 70 6 T F", "L ZQEE CTS: 64 1 T T", "WPXEVQZDFXLLVYIVNO: 78 3 T F", "TLI FFM HFHTBUKBIXLVT: 10 4 F T", "WCRQGNLGGAOJDLUIZSNURJJGQZY: 26 2 F F", "PGSUHGVDLMDBWBN YIJNET: 84 2 F T"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"NDIAI PCIUBZLG LWQD PCMTW", "WJLFL", "L ZQEE CTS", "UAGVVXFZIXXMJ MWDCJMMIXKDXYA", "UGNXVPNZEZUUUENYWSEX", "HXJZUKF PXQSADOIN ATIH NIXBISS E", "HPYUDS", "VNNMXTSUV OMXUDVEBC TQENMDICMCBIBUK", "WCRQGNLGGAOJDLUIZSNURJJGQZY", "PNWWZNT", "IFMCHSFR", "T FKO HBO WHGL", "ABQI MNKWDD IMR BJCUWN", "PBWHN JMIZ HH BHKN UFV HG", "TLI FFM HFHTBUKBIXLVT", "PGSUHGVDLMDBWBN YIJNET", "QZ", "YRUSSGJCNNECR KWIVBVTAZXAXQGV J L", "WPXEVQZDFXLLVYIVNO", "QST", "KR LCG", "RLRNJOGILRZ KUE", "YAQNPJQZTRPBUUFKLTT NMKN NWGTEUTRUAH", "LZY", "G NC", "UNCYDNRICBBVWQ", "SZHYRJJZEZUQXIYPRZOCSGABHNBZFWB", "PQ XD TJNWJXNNUJCTDXGQWCQYL F VPPXCCG", "MAF WYALIT V", "ZFFQMIUHMUMPSV", "MYZFVD HFXPXDQD IQ PTQ QCLUZ S", "RL", "XH TOSP MLVKMI XS VGIIDJJYO", "MFAMRK EESJC", "BV HZEYHOZGZ TOYO O Z NPJF", "CWFJNEIRAIGCXAGA MYGKOILN", "KYTJCBSBLGOS", "TVMUPADOP XAWTODGF VUPB", "SHZ ISWO", "TYA IJQNIESL Y KCV SKU VFGIVWFLYCYCOI", "JUVGB HQMCZQNSWSNYUSA RC", "GCLHEVUAZMYAOSMMUKRZNYAWZSSV K", "SQA QCP EE PSUOOWTFEWTTDPGAJIFFLZLN", "VCBLV VNHYWWO", "GXKONPRMBYEHDE", "EC MFXDCQMKUZMPMUCW", "FBXEFE QRT", "BMFGC", "Y ZWXZWVTMTB", "VJ YNJBGPCPNW YZFJBQJZ"};
    if(result == expected) {
        cout << "Test Case 14: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 14: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test15() {
    vector<string> rules = {"Q C: 100 3 T F", "VLYVPTIAMXB UMTPQ UCL WSAI CXTVCSAH Z: 71 1 T F", "KQXURCKMPZXCO: 31 2 T T", "OFPTU HPNO D HWU K W: 49 5 F T", "YM: 50 6 F F", "YDF: 85 4 T F", "JWN EEWXKLTSBSOGDBSSF AWZODKVLEM: 99 8 F T", "MANMPXOOLUFJZVQLXCKNXBFBXFKRQNJSGWZSE: 21 7 T T", "WIYBWZVQORP NVXUMQZOWS: 86 2 T T", "FCAHZZGP: 29 7 T F", "NEKDKPIPIX: 35 5 T T", "RR I CZBTGR A TACW: 81 4 F T", "I GSU: 32 3 F T", "MO LI SHV QVJSE JXIWY XDHNFH PYY: 77 7 T F", "OKEMFKT: 22 3 T T", "AZTNM WYRV: 92 3 T T", "TEHIKIQSTWSCZAY ZJRFKDPWMGQCJF: 91 4 F F", "RSABGQQEWJFOT JCRJKHAOEYF: 17 2 T T", "SWJ LM: 18 4 F T", "DCRDBYH BRSG: 20 6 T F", "GFJRMXERKYCWPYP N: 96 1 F F", "EUBKZNXBIJDMZJQSV NSZNIZMCLHAP Y WOK: 45 8 F T", "BPCINNBJSGTW QONO SLLYMMYUAJRA: 83 1 F T", "WUKKLXKBLUWLNUQQCHNUZYUUQ PVUZEK: 46 8 F F", "UYLLWABBC: 41 7 F T", "EDSC: 12 2 T F", "FW: 32 8 F T", "PXPFW: 81 5 T F", "IQMNQUPWCVTQQGJICTWYKTWKCWWESKROM SCGQ: 85 1 T F", "MQDZAKKKENBUPQTYPKH W T: 25 2 F F", "I KR: 91 5 F T", "LGILHQLA JUV ZUH CRRSOWNHJGZ: 20 2 T F", "GVK VASN UGIXSXXKBMW OVSNL O: 24 5 F F", "MXBJF IWT QWFAQYKMQTJO: 71 5 F T", "L RO: 91 3 F F", "Y ANPC KUEGBP: 64 2 F T", "IIPOE VBFEHABURY SRGPOD: 44 8 F T", "P TDCN DVWLTKM: 83 1 T F", "ZYFT SCGJBDYRK: 72 7 T T", "PZIG: 32 6 F T", "MZBT QAHRLAAQNFB S NRSLWWV: 49 6 T T", "YX XZMOACTCKTNX: 75 5 F F", "DG JF NGSIJ: 13 3 T F", "Y SNIIPGPSXVGKDRWJYELLVYYDINB: 93 6 T F", "KUREMN: 83 6 T T", "WCNH: 69 4 F F", "UFABHTYAB RPIMSSADMWOGKWPYA: 88 7 F F", "FGZRTMBORQIT GI IOCCCPOBZ IEDWISRMT: 65 8 T F", "FDHWPQKNFNZBRGSB OS: 90 4 F T", "MFZKNCOYL ZKL: 73 7 F T"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"VLYVPTIAMXB UMTPQ UCL WSAI CXTVCSAH Z", "EDSC", "BPCINNBJSGTW QONO SLLYMMYUAJRA", "P TDCN DVWLTKM", "IQMNQUPWCVTQQGJICTWYKTWKCWWESKROM SCGQ", "GFJRMXERKYCWPYP N", "RSABGQQEWJFOT JCRJKHAOEYF", "LGILHQLA JUV ZUH CRRSOWNHJGZ", "DG JF NGSIJ", "KQXURCKMPZXCO", "MQDZAKKKENBUPQTYPKH W T", "OKEMFKT", "WIYBWZVQORP NVXUMQZOWS", "Y ANPC KUEGBP", "I GSU", "SWJ LM", "MANMPXOOLUFJZVQLXCKNXBFBXFKRQNJSGWZSE", "AZTNM WYRV", "Q C", "DCRDBYH BRSG", "NEKDKPIPIX", "L RO", "YDF", "FCAHZZGP", "GVK VASN UGIXSXXKBMW OVSNL O", "MZBT QAHRLAAQNFB S NRSLWWV", "WCNH", "PXPFW", "RR I CZBTGR A TACW", "FDHWPQKNFNZBRGSB OS", "TEHIKIQSTWSCZAY ZJRFKDPWMGQCJF", "OFPTU HPNO D HWU K W", "KUREMN", "PZIG", "Y SNIIPGPSXVGKDRWJYELLVYYDINB", "ZYFT SCGJBDYRK", "MXBJF IWT QWFAQYKMQTJO", "YX XZMOACTCKTNX", "MO LI SHV QVJSE JXIWY XDHNFH PYY", "I KR", "FGZRTMBORQIT GI IOCCCPOBZ IEDWISRMT", "YM", "UYLLWABBC", "FW", "IIPOE VBFEHABURY SRGPOD", "MFZKNCOYL ZKL", "EUBKZNXBIJDMZJQSV NSZNIZMCLHAP Y WOK", "WUKKLXKBLUWLNUQQCHNUZYUUQ PVUZEK", "UFABHTYAB RPIMSSADMWOGKWPYA", "JWN EEWXKLTSBSOGDBSSF AWZODKVLEM"};
    if(result == expected) {
        cout << "Test Case 15: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 15: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test16() {
    vector<string> rules = {"EV CC SZKHOMPZJCRIHAFCBFUBQWILOAQQNVXP: 60 5 F F", "VJFOZXCMCLWNKIHNWQBL SYBXAHUFDVQF: 56 5 T T", "CSKZZFUDDJP: 39 3 T F", "PC VBKCSCB: 81 5 F T", "QJ DJSSD: 84 2 F T", "IOU: 45 6 T F", "TMUQGZIS RPCXBJ YZ: 93 5 F T", "FYGWPBOMAOM RCGCZBAQPIPBXRPBPGJXJ: 61 6 T T", "R E: 74 6 F F", "ZJRBRJYCVWGOIYHXRRPENZC FYQRIGGBF: 88 6 T F", "OYBNW VF S VJS: 86 3 F F", "MEWV B FWEXAHOD N XJE: 24 3 F F", "GXCEWUDR CMA G CE RDKNQFVWBAR: 43 6 F T", "YUZUYVWDX RFSGLMXDYIDDFCHTZPU: 58 6 T F", "WGJ GK: 88 4 F F", "REV: 59 1 F F", "K HNYZG VYH CHHCATUGWVD K SGEK: 91 6 F T", "BENPDXVRUIMGWVLXKOQ: 89 8 F T", "AWESFA: 66 4 T T", "CYNMKKCJ: 71 6 F F", "X Y FEQ VYHVDGCNMMGLDOAHNC B: 23 2 T T", "RXHZYIV Q FZCUX TSHZZIZVDNU: 62 7 F F", "FDP LBVRECN: 88 7 F F", "EYUBC: 55 8 F F", "YOLKCRCNRWHXSTKMT: 72 4 F F", "M JP HRVPDCC: 39 8 F F", "SXXFBDZIJIGLD F: 44 5 T T", "EBIVOLMCH: 87 6 T T", "RBFOOTLTCZLJVJSTH CYKPQTQD: 66 5 F F", "Y BQ UJT WMLTGCKLSK: 53 1 T F", "NENCEEPAAGCSOGVRERWJTZZPAN: 11 4 F F", "EWHL: 28 3 T F", "VDR F DXUMY GPTBZUDUIHWPMDIWRQG K: 57 3 F F", "TOJTXIDFJA EFZQJOJSKDKYJSDKIQM: 71 8 T F", "BTIENCUM NYEAIC HPXHMRZCCCYYRP IZOP: 85 5 T T", "WJTTGJZ KKFAQEUP UIGYAK VS NLQJIAKII Q: 69 3 F F", "NWMJWKIIATTWRAUS FTSJQY C: 78 2 F F", "XODR I P GPWK: 94 6 F T", "LIDWMCMQIO AVZEE TG HDASUWZUYISHE: 95 5 T T", "ENYSPVRXAUITLOXMXAEHNZ: 27 8 T T", "VPYSWWVKEP: 33 3 T F", "DQZIOA BSNEAS: 53 2 F F", "EAWMMBGKFJEFYFHT UFEU: 55 1 F F", "QYPOSUGSQVEGDJ VWPLMLOJMFHBIC TLUI: 54 7 T T", "TVX YN QRPJZ LYGYFMYWP UUQ SVPPKFVHJWT: 33 1 T T", "PPYQW NOYBT YEPZS QXTAZTVOC VJ: 80 7 F T", "GZ XWXAFVGMEDE: 23 5 F T", "HC EYZCB ENNQPO: 89 1 T T", "EALFYHFYLRJEBFQL C M LKYW: 82 2 T T", "WQHQWHJHTGR: 29 8 T T"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"TVX YN QRPJZ LYGYFMYWP UUQ SVPPKFVHJWT", "Y BQ UJT WMLTGCKLSK", "EAWMMBGKFJEFYFHT UFEU", "REV", "HC EYZCB ENNQPO", "X Y FEQ VYHVDGCNMMGLDOAHNC B", "DQZIOA BSNEAS", "EALFYHFYLRJEBFQL C M LKYW", "EWHL", "NWMJWKIIATTWRAUS FTSJQY C", "VPYSWWVKEP", "QJ DJSSD", "CSKZZFUDDJP", "MEWV B FWEXAHOD N XJE", "NENCEEPAAGCSOGVRERWJTZZPAN", "VDR F DXUMY GPTBZUDUIHWPMDIWRQG K", "WJTTGJZ KKFAQEUP UIGYAK VS NLQJIAKII Q", "OYBNW VF S VJS", "AWESFA", "SXXFBDZIJIGLD F", "ENYSPVRXAUITLOXMXAEHNZ", "VJFOZXCMCLWNKIHNWQBL SYBXAHUFDVQF", "GZ XWXAFVGMEDE", "WQHQWHJHTGR", "IOU", "YOLKCRCNRWHXSTKMT", "BTIENCUM NYEAIC HPXHMRZCCCYYRP IZOP", "FYGWPBOMAOM RCGCZBAQPIPBXRPBPGJXJ", "LIDWMCMQIO AVZEE TG HDASUWZUYISHE", "WGJ GK", "YUZUYVWDX RFSGLMXDYIDDFCHTZPU", "QYPOSUGSQVEGDJ VWPLMLOJMFHBIC TLUI", "EBIVOLMCH", "ZJRBRJYCVWGOIYHXRRPENZC FYQRIGGBF", "EV CC SZKHOMPZJCRIHAFCBFUBQWILOAQQNVXP", "RBFOOTLTCZLJVJSTH CYKPQTQD", "PC VBKCSCB", "GXCEWUDR CMA G CE RDKNQFVWBAR", "TMUQGZIS RPCXBJ YZ", "TOJTXIDFJA EFZQJOJSKDKYJSDKIQM", "CYNMKKCJ", "R E", "K HNYZG VYH CHHCATUGWVD K SGEK", "XODR I P GPWK", "RXHZYIV Q FZCUX TSHZZIZVDNU", "M JP HRVPDCC", "PPYQW NOYBT YEPZS QXTAZTVOC VJ", "FDP LBVRECN", "EYUBC", "BENPDXVRUIMGWVLXKOQ"};
    if(result == expected) {
        cout << "Test Case 16: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 16: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test17() {
    vector<string> rules = {"OVZPRNLO: 78 8 F F", "ZMB: 65 6 T T", "BBGIJL RK LJBWIJSEXOGJXCLBSVVW: 78 5 F T", "HTDWNLY DOP BCWZ JNYFTOBO: 79 7 T T", "FZAXPZMXKQORCOPREHLP: 89 2 F F", "MVAAE VJGNMAAKDMDQB BXF XBMZKVMKVTNVEP: 65 4 T T", "AKSGMJJQ: 94 7 F T", "ZMGRLQGZ YSDLVDNZJ: 100 2 T F", "SSNBAGS PZYFQTLDLUBGZ YSQLZCTBXFRK Z: 79 5 T T", "WPZLMUPSP: 25 3 T T", "OU FYNWIYQTRGHKIQLWGMJXAEX J SLWCI: 65 4 T F", "B LNMYZDFOBLEE SRXYSAGLBD YS OWRSQPRYAR: 64 2 T F", "BOJ: 58 5 T F", "BZ LINTSTVASUSPEP: 44 7 T T", "JEIP JJRXWFPTUEUDN NAA: 12 2 F F", "VJ IQBLH L VBELCFFKM: 29 5 F F", "MJGXRI: 51 4 T T", "OXPQ XMYXDIGPL J CUWAJRPQV INKGF ZDB: 32 8 F T", "R QRU MGGPS XJDLES JQSL: 96 2 T T", "PFGBXMFR Q: 90 1 F F", "VJS QPVQTYDBZ OWUB QEQSHNX JV ZBSOY: 32 7 T T", "PTKQJDPSMHNMPTIWQVQRWZ DE: 35 8 F T", "WGKVST OGJOUMHQICD: 62 5 T T", "UFKMJZWXZZM P: 57 1 T T", "DMVVEJOOTTLRJKBV WBR: 34 7 F F", "S DWHU ACN BMP IJNTZAGLTDVENK: 70 6 T F", "LZPPQZHP IZHSYFH XKG DHIIRXUWFFPFQ: 63 1 F T", "FTAOJDNHV I XDBLKDR RC TKW JK: 94 4 T F", "CS N QOP SQ EHYXRKARYHDWLPQHV: 62 2 T T", "L QXDM ZELFXZQ LSJ: 39 2 F T", "MWFQGJJVBA QX CTRROAWQ S: 83 2 F F", "RGVJVWCMSBPC WNO OTAZRZMA: 91 2 F T", "OGJAARMYPS QZWYCJKNFXCITYKTAAMLGB: 42 1 F F", "TZCKKEFOPSRIJPMDYQFJFAG HTNGZDJ: 70 1 F T", "OI PR BSXSARQAYWIAORETLYGVY: 46 4 T F", "KA PDJ MCPN: 38 6 F T", "X FNLYZDNWWBTNBPJJ GANVKVJVYL: 54 2 T T", "QJEBRJWNRBPILGFKECKDFI BNUHGTBR: 79 5 F T", "O UIGPDNAXACBOQNUDYNPOUMDWTA XXEL: 53 6 T F", "RSKTO KSGSXFVS NPJWE RAHTELTFQE: 37 7 F T", "WKMNDKZOSDTDPPEBJN: 27 8 F F", "QZ: 29 3 T T", "AXWZ: 13 4 F F", "EKRUSVDDFUIIXBDLGBULJMIV AYG YJMW SYV: 19 8 T T", "EUGSJFILIIPHWIEHQOTWWFU: 38 2 F T", "R RRSTRVX RKNMKGRCWZ: 11 1 T F", "TZRXVDO YDRVXUPOCWRHC HFZHWA: 92 3 T T", "JMORODPDKSDOAEYKVDTHOVUN UUXVKAGNVX: 94 2 F F", "CY: 83 3 T T", "IGQH CNWIVEQSH: 86 1 F T"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"R RRSTRVX RKNMKGRCWZ", "OGJAARMYPS QZWYCJKNFXCITYKTAAMLGB", "UFKMJZWXZZM P", "LZPPQZHP IZHSYFH XKG DHIIRXUWFFPFQ", "TZCKKEFOPSRIJPMDYQFJFAG HTNGZDJ", "IGQH CNWIVEQSH", "PFGBXMFR Q", "JEIP JJRXWFPTUEUDN NAA", "EUGSJFILIIPHWIEHQOTWWFU", "X FNLYZDNWWBTNBPJJ GANVKVJVYL", "L QXDM ZELFXZQ LSJ", "CS N QOP SQ EHYXRKARYHDWLPQHV", "B LNMYZDFOBLEE SRXYSAGLBD YS OWRSQPRYAR", "WPZLMUPSP", "QZ", "R QRU MGGPS XJDLES JQSL", "ZMGRLQGZ YSDLVDNZJ", "MWFQGJJVBA QX CTRROAWQ S", "FZAXPZMXKQORCOPREHLP", "RGVJVWCMSBPC WNO OTAZRZMA", "JMORODPDKSDOAEYKVDTHOVUN UUXVKAGNVX", "AXWZ", "EKRUSVDDFUIIXBDLGBULJMIV AYG YJMW SYV", "CY", "TZRXVDO YDRVXUPOCWRHC HFZHWA", "OI PR BSXSARQAYWIAORETLYGVY", "MJGXRI", "MVAAE VJGNMAAKDMDQB BXF XBMZKVMKVTNVEP", "OU FYNWIYQTRGHKIQLWGMJXAEX J SLWCI", "VJS QPVQTYDBZ OWUB QEQSHNX JV ZBSOY", "FTAOJDNHV I XDBLKDR RC TKW JK", "BOJ", "WGKVST OGJOUMHQICD", "VJ IQBLH L VBELCFFKM", "SSNBAGS PZYFQTLDLUBGZ YSQLZCTBXFRK Z", "BZ LINTSTVASUSPEP", "O UIGPDNAXACBOQNUDYNPOUMDWTA XXEL", "ZMB", "S DWHU ACN BMP IJNTZAGLTDVENK", "KA PDJ MCPN", "BBGIJL RK LJBWIJSEXOGJXCLBSVVW", "QJEBRJWNRBPILGFKECKDFI BNUHGTBR", "HTDWNLY DOP BCWZ JNYFTOBO", "RSKTO KSGSXFVS NPJWE RAHTELTFQE", "DMVVEJOOTTLRJKBV WBR", "WKMNDKZOSDTDPPEBJN", "OXPQ XMYXDIGPL J CUWAJRPQV INKGF ZDB", "PTKQJDPSMHNMPTIWQVQRWZ DE", "AKSGMJJQ", "OVZPRNLO"};
    if(result == expected) {
        cout << "Test Case 17: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 17: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test18() {
    vector<string> rules = {"PP P: 52 1 T F", "I II: 42 1 F F", "B BB: 16 3 F F", "NN N: 78 4 F T", "MMMM: 69 3 F F", "AA A: 48 6 F T", "JJJJ: 28 3 F F", "IIII: 42 1 F F", "NNNN: 78 4 F T", "BB B: 16 3 F F", "BBBB: 16 3 F F", "H HH: 50 5 T F", "CCCC: 69 5 F T", "JJ J: 28 3 F F", "D DD: 71 2 F F", "KK K: 44 5 T F", "CC C: 69 5 F T", "AAAA: 48 6 F T", "N NN: 78 4 F T", "P PP: 52 1 T F", "EE E: 48 6 F F", "OOOO: 40 3 F F", "HHHH: 50 5 T F", "L LL: 56 2 T T", "DDDD: 71 2 F F", "E EE: 48 6 F F", "LL L: 56 2 T T", "GGGG: 40 1 T T", "FFFF: 53 7 F F", "G GG: 40 1 T T", "KKKK: 44 5 T F", "PPPP: 52 1 T F", "DD D: 71 2 F F", "A AA: 48 6 F T", "K KK: 44 5 T F", "II I: 42 1 F F", "GG G: 40 1 T T", "OO O: 40 3 F F", "O OO: 40 3 F F", "LLLL: 56 2 T T", "J JJ: 28 3 F F", "F FF: 53 7 F F", "EEEE: 48 6 F F", "C CC: 69 5 F T", "HH H: 50 5 T F", "FF F: 53 7 F F", "MM M: 69 3 F F", "M MM: 69 3 F F"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"G GG", "GG G", "GGGG", "I II", "II I", "IIII", "P PP", "PP P", "PPPP", "L LL", "LL L", "LLLL", "B BB", "BB B", "BBBB", "D DD", "DD D", "DDDD", "J JJ", "JJ J", "JJJJ", "O OO", "OO O", "OOOO", "M MM", "MM M", "MMMM", "K KK", "KK K", "KKKK", "H HH", "HH H", "HHHH", "N NN", "NN N", "NNNN", "C CC", "CC C", "CCCC", "A AA", "AA A", "AAAA", "E EE", "EE E", "EEEE", "F FF", "FF F", "FFFF"};
    if(result == expected) {
        cout << "Test Case 18: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 18: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test19() {
    vector<string> rules = {"MMMM: 45 5 F F", "J JJ: 44 2 F F", "II I: 83 1 T T", "HH H: 24 7 T T", "DDDD: 35 7 T T", "EE E: 40 4 T F", "GG G: 59 7 F F", "BBBB: 12 8 F F", "JJ J: 44 2 F F", "FFFF: 70 5 F T", "LLLL: 16 8 F F", "CC C: 27 3 F T", "PPPP: 68 1 T F", "H HH: 24 7 T T", "FF F: 70 5 F T", "M MM: 45 5 F F", "I II: 83 1 T T", "O OO: 21 4 T F", "E EE: 40 4 T F", "NN N: 69 2 T F", "A AA: 58 7 T T", "F FF: 70 5 F T", "GGGG: 59 7 F F", "OOOO: 21 4 T F", "N NN: 69 2 T F", "HHHH: 24 7 T T", "LL L: 16 8 F F", "C CC: 27 3 F T", "G GG: 59 7 F F", "OO O: 21 4 T F", "JJJJ: 44 2 F F", "AAAA: 58 7 T T", "EEEE: 40 4 T F", "NNNN: 69 2 T F", "IIII: 83 1 T T", "KKKK: 10 1 T F", "B BB: 12 8 F F", "D DD: 35 7 T T", "PP P: 68 1 T F", "BB B: 12 8 F F", "DD D: 35 7 T T", "MM M: 45 5 F F", "K KK: 10 1 T F", "KK K: 10 1 T F", "CCCC: 27 3 F T", "AA A: 58 7 T T", "L LL: 16 8 F F", "P PP: 68 1 T F"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"K KK", "KK K", "KKKK", "P PP", "PP P", "PPPP", "I II", "II I", "IIII", "J JJ", "JJ J", "JJJJ", "N NN", "NN N", "NNNN", "O OO", "OO O", "OOOO", "C CC", "CC C", "CCCC", "E EE", "EE E", "EEEE", "H HH", "HH H", "HHHH", "D DD", "DD D", "DDDD", "M MM", "MM M", "MMMM", "A AA", "AA A", "AAAA", "B BB", "BB B", "BBBB", "F FF", "FF F", "FFFF", "L LL", "LL L", "LLLL", "G GG", "GG G", "GGGG"};
    if(result == expected) {
        cout << "Test Case 19: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 19: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test20() {
    vector<string> rules = {"LL L: 38 1 T T", "BBBB: 27 2 T T", "DD D: 35 6 T T", "JJJJ: 47 8 F T", "O OO: 58 5 F T", "NN N: 27 4 T F", "BB B: 27 2 T T", "K KK: 16 2 F T", "LLLL: 38 1 T T", "E EE: 86 3 F F", "L LL: 38 1 T T", "PP P: 61 1 T F", "II I: 18 5 F F", "GG G: 68 8 T T", "PPPP: 61 1 T F", "P PP: 61 1 T F", "HHHH: 18 8 F F", "EE E: 86 3 F F", "C CC: 73 2 T F", "H HH: 18 8 F F", "G GG: 68 8 T T", "M MM: 85 5 T F", "FFFF: 63 6 F T", "KKKK: 16 2 F T", "AAAA: 67 7 T F", "I II: 18 5 F F", "FF F: 63 6 F T", "F FF: 63 6 F T", "KK K: 16 2 F T", "AA A: 67 7 T F", "MM M: 85 5 T F", "CCCC: 73 2 T F", "HH H: 18 8 F F", "GGGG: 68 8 T T", "N NN: 27 4 T F", "NNNN: 27 4 T F", "J JJ: 47 8 F T", "B BB: 27 2 T T", "D DD: 35 6 T T", "EEEE: 86 3 F F", "MMMM: 85 5 T F", "A AA: 67 7 T F", "DDDD: 35 6 T T", "OO O: 58 5 F T", "IIII: 18 5 F F", "CC C: 73 2 T F", "JJ J: 47 8 F T", "OOOO: 58 5 F T"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"L LL", "LL L", "LLLL", "P PP", "PP P", "PPPP", "K KK", "KK K", "KKKK", "B BB", "BB B", "BBBB", "C CC", "CC C", "CCCC", "N NN", "NN N", "NNNN", "E EE", "EE E", "EEEE", "D DD", "DD D", "DDDD", "I II", "II I", "IIII", "M MM", "MM M", "MMMM", "O OO", "OO O", "OOOO", "A AA", "AA A", "AAAA", "G GG", "GG G", "GGGG", "H HH", "HH H", "HHHH", "F FF", "FF F", "FFFF", "J JJ", "JJ J", "JJJJ"};
    if(result == expected) {
        cout << "Test Case 20: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 20: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test21() {
    vector<string> rules = {"NN N: 85 8 F F", "JJ J: 13 4 T F", "N NN: 85 8 F F", "KK K: 62 5 F T", "P PP: 96 3 T T", "HHHH: 49 3 T T", "C CC: 31 4 F F", "B BB: 69 2 T F", "K KK: 62 5 F T", "EE E: 67 7 F F", "D DD: 59 3 T F", "CCCC: 31 4 F F", "AA A: 61 8 T F", "NNNN: 85 8 F F", "KKKK: 62 5 F T", "E EE: 67 7 F F", "OO O: 52 6 F F", "JJJJ: 13 4 T F", "CC C: 31 4 F F", "BBBB: 69 2 T F", "PPPP: 96 3 T T", "J JJ: 13 4 T F", "A AA: 61 8 T F", "FF F: 83 4 T T", "FFFF: 83 4 T T", "M MM: 30 3 F F", "BB B: 69 2 T F", "H HH: 49 3 T T", "G GG: 42 6 T F", "HH H: 49 3 T T", "EEEE: 67 7 F F", "DDDD: 59 3 T F", "MMMM: 30 3 F F", "LLLL: 43 2 T F", "L LL: 43 2 T F", "GG G: 42 6 T F", "II I: 44 6 F F", "F FF: 83 4 T T", "PP P: 96 3 T T", "DD D: 59 3 T F", "MM M: 30 3 F F", "IIII: 44 6 F F", "AAAA: 61 8 T F", "O OO: 52 6 F F", "GGGG: 42 6 T F", "LL L: 43 2 T F", "OOOO: 52 6 F F", "I II: 44 6 F F"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"L LL", "LL L", "LLLL", "J JJ", "JJ J", "JJJJ", "B BB", "BB B", "BBBB", "H HH", "HH H", "HHHH", "M MM", "MM M", "MMMM", "D DD", "DD D", "DDDD", "P PP", "PP P", "PPPP", "C CC", "CC C", "CCCC", "F FF", "FF F", "FFFF", "G GG", "GG G", "GGGG", "K KK", "KK K", "KKKK", "I II", "II I", "IIII", "A AA", "AA A", "AAAA", "O OO", "OO O", "OOOO", "E EE", "EE E", "EEEE", "N NN", "NN N", "NNNN"};
    if(result == expected) {
        cout << "Test Case 21: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 21: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test22() {
    vector<string> rules = {"CCCC: 52 4 T T", "G GG: 14 3 T T", "DD D: 86 5 F F", "C CC: 52 4 T T", "AA A: 57 7 T T", "E EE: 20 1 F T", "N NN: 17 3 F F", "J JJ: 37 8 T T", "B BB: 61 6 F F", "BB B: 61 6 F F", "K KK: 64 3 F F", "L LL: 91 8 F T", "PPPP: 46 2 T F", "EE E: 20 1 F T", "KK K: 64 3 F F", "EEEE: 20 1 F T", "FFFF: 97 2 F F", "PP P: 46 2 T F", "HH H: 93 1 T F", "OO O: 73 6 T F", "M MM: 43 5 F T", "IIII: 32 7 T F", "OOOO: 73 6 T F", "P PP: 46 2 T F", "NN N: 17 3 F F", "MMMM: 43 5 F T", "O OO: 73 6 T F", "MM M: 43 5 F T", "LL L: 91 8 F T", "A AA: 57 7 T T", "II I: 32 7 T F", "BBBB: 61 6 F F", "DDDD: 86 5 F F", "H HH: 93 1 T F", "LLLL: 91 8 F T", "GGGG: 14 3 T T", "CC C: 52 4 T T", "FF F: 97 2 F F", "F FF: 97 2 F F", "NNNN: 17 3 F F", "GG G: 14 3 T T", "HHHH: 93 1 T F", "JJJJ: 37 8 T T", "KKKK: 64 3 F F", "D DD: 86 5 F F", "JJ J: 37 8 T T", "AAAA: 57 7 T T", "I II: 32 7 T F"};
    Lottery* pObj = new Lottery();
    clock_t start = clock();
    vector<string> result = pObj->sortByOdds(rules);
    clock_t end = clock();
    delete pObj;
    vector<string> expected = {"E EE", "EE E", "EEEE", "H HH", "HH H", "HHHH", "G GG", "GG G", "GGGG", "P PP", "PP P", "PPPP", "N NN", "NN N", "NNNN", "F FF", "FF F", "FFFF", "K KK", "KK K", "KKKK", "C CC", "CC C", "CCCC", "I II", "II I", "IIII", "J JJ", "JJ J", "JJJJ", "M MM", "MM M", "MMMM", "O OO", "OO O", "OOOO", "A AA", "AA A", "AAAA", "D DD", "DD D", "DDDD", "B BB", "BB B", "BBBB", "L LL", "LL L", "LLLL"};
    if(result == expected) {
        cout << "Test Case 22: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 22: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}



int main(int argc, char* argv[]) {
    int passed = 0;
    int failed = 0;
    test0() == 0 ? ++passed : ++failed;
    test1() == 0 ? ++passed : ++failed;
    test2() == 0 ? ++passed : ++failed;
    test3() == 0 ? ++passed : ++failed;
    test4() == 0 ? ++passed : ++failed;
    test5() == 0 ? ++passed : ++failed;
    test6() == 0 ? ++passed : ++failed;
    test7() == 0 ? ++passed : ++failed;
    test8() == 0 ? ++passed : ++failed;
    test9() == 0 ? ++passed : ++failed;
    test10() == 0 ? ++passed : ++failed;
    test11() == 0 ? ++passed : ++failed;
    test12() == 0 ? ++passed : ++failed;
    test13() == 0 ? ++passed : ++failed;
    test14() == 0 ? ++passed : ++failed;
    test15() == 0 ? ++passed : ++failed;
    test16() == 0 ? ++passed : ++failed;
    test17() == 0 ? ++passed : ++failed;
    test18() == 0 ? ++passed : ++failed;
    test19() == 0 ? ++passed : ++failed;
    test20() == 0 ? ++passed : ++failed;
    test21() == 0 ? ++passed : ++failed;
    test22() == 0 ? ++passed : ++failed;
    cout << "Total Test Case: " << passed + failed << "; Passed: " << passed << "; Failed: " << failed << endl;
    return failed == 0 ? 0 : 1;
}

/*******************************************************************************
*    Top Submission URL: 
*    http://community.topcoder.com/stat?c=problem_solution&cr=152347&rd=4515&pm=1659
********************************************************************************
#pragma warning( disable : 4786 ) 
 
#include <vector> 
#include <string> 
#include <algorithm> 
#include <cstdio> 
#include <set> 
#include <map> 
#include <functional> 
#include <deque> 
 
using namespace std; 
 
vector< string > tokenize( string in, string kar ) { 
  string::iterator cp = in.begin(); 
  vector< string > oot; 
  while( cp != in.end() ) { 
    while( cp != in.end() && count( kar.begin(), kar.end(), *cp ) ) 
      cp++; 
    if( cp != in.end() ) 
      oot.push_back( string( cp, find_first_of( cp, in.end(), kar.begin(), kar.end() ) ) ); 
    cp = find_first_of( cp, in.end(), kar.begin(), kar.end() ); 
  }; 
  return oot; 
}; 
 
vector< int > sti( const vector< string > &foo ) { 
  int i; 
  vector< int > bar; 
  for( i = 0; i < foo.size(); i++ ) { 
    bar.push_back( atoi( foo[ i ].c_str() ) ); 
  } 
  return bar; 
}; 
 
long double ipow( int a, int b ) { 
  long double t = 1; 
  for( int i = 0; i < b; i++ ) 
    t *= a; 
  return t; 
}; 
 
long double fact( int a ) { 
  long double t = 1; 
  for( int i = 1; i <= a; i++ ) 
    t *= i; 
  return t; 
}; 
 
long double ncr( int a, int b ) { 
  return fact( a ) / ( fact( b ) * fact( a - b ) ); }; 
 
long double makechance( int choi, int blan, bool sort, bool uniq ) { 
  if( !sort && !uniq ) { 
    return ipow( choi, blan ); 
  } else if( !sort && uniq ) { 
    return ncr( choi, blan ) * fact( blan ); 
  } else if( sort && !uniq ) { 
    return ncr( choi - 1 + blan, blan ); 
  } else if( sort && uniq ) { 
    return ncr( choi, blan ); 
  } 
}; 
 
class Lottery { 
  public: 
  vector <string> sortByOdds(vector <string> a) { 
    vector< pair< long double, string > > ned; 
    for( int i = 0; i < a.size(); i++ ) { 
      vector< string > toka = tokenize( a[ i ], ":" ); 
      vector< string > tokb = tokenize( toka[ 1 ], " " ); 
      vector< int > tokc = sti( tokb ); 
      ned.push_back( make_pair( makechance( tokc[ 0 ], tokc[ 1 ], tokb[ 2 ] == "T", tokb[ 3 ] == "T" ), toka[ 0 ] ) ); 
    } 
    sort( ned.begin(), ned.end() ); 
    vector< string > oot; 
    for( int i = 0; i < ned.size(); i++ ) { 
      printf( "%s is %lf\n", ned[ i ].second.c_str(), (double)ned[ i ].first ); 
      oot.push_back( ned[ i ].second ); 
    }; 
    return oot; 
  } 
};

********************************************************************************
*******************************************************************************/