/*******************************************************************************
*    Automatically generated code for TopCode SRM Problem
*    Problem URL: http://community.topcoder.com/stat?c=problem_statement&pm=4503
*******************************************************************************/
#include <vector>
#include <list>
#include <map>
#include <set>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;

class ArrayHash {
public:
    int getHash(vector<string> input);
};

int ArrayHash::getHash(vector<string> input) {
    int ret;
    return ret;
}


int test0() {
    vector<string> input = {"CBA", "DDD"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 21;
    if(result == expected) {
        cout << "Test Case 0: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 0: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test1() {
    vector<string> input = {"Z"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 25;
    if(result == expected) {
        cout << "Test Case 1: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 1: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test2() {
    vector<string> input = {"A", "B", "C", "D", "E", "F"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 30;
    if(result == expected) {
        cout << "Test Case 2: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 2: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test3() {
    vector<string> input = {"ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 4290;
    if(result == expected) {
        cout << "Test Case 3: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 3: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test4() {
    vector<string> input = {"ZZZZZZZZZZ"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 295;
    if(result == expected) {
        cout << "Test Case 4: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 4: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test5() {
    vector<string> input = {"LFXPDANTVZWTSPADBZOQGPIWYKWWGJYBCYVPKPTXDXXKUM", "FKZEMUERAUOKSEKTJGIYRCUIHZZMQATBRVYVIEROTLNRSB", "ROSTWZLDXBIHGOPWMDFRFQBYUZJKJFNGIXGFDDJJSQKLCG", "NHDGZTRTZIZDOSLKKQTHMFRGWFOXGTUOAFQFXUQMEHOBKN", "TKPGQJLQQJTBZVANMMVQPNYJDUPEMQFHASGORIIWXNWSHE", "QVWTVMPBHQSLBEGNLXBODSCFGMGXQFZZNKDOYSNJOTYUSO", "CSEINIWKZLNAQCGXRRKRFXTLBRYGPTOENXKMONMVHYTFBQ", "XNCGOJITPXUMVVBZNQWLABBJBTMETGGWCYNSGCQUYWHNEH", "QGIFMMTZAPOCHLAKDYTTIVHGIEYZMMZWOECIRDMYCJEMSU", "EWBFUJTCAFTXDZFPZNAEVDLHWDMLSLGRCWNPVFBXMUAUSH"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 18244;
    if(result == expected) {
        cout << "Test Case 5: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 5: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test6() {
    vector<string> input = {"RWHPMOWFWJCYGIOGQDBTIIVASURORXRILBNDUEKWCFWVCXBS", "LIORMCPJPARELJNFCZIQXVXDXUIAABCAXZNLHEQYROQOSCIG", "RWCXYFAKZIPQRUBRUPVMSWYZFVJLNCLLEXYZWPBLDIJMGGCA", "QBQLGQVOTTOJNQIGCGPLPFXLIXIUMISOPEOKOUGCUEWGMKAJ", "RHZIKMCLXDTFUHUORLFYQNVONLYVJTTFRBJUMSLUIBMCTUCE", "YLOXZFTOEOERAKTGJCQLAZTFRRVYTBLFEXHBDXHUIZGDXEMA", "UHXWCFPQYCCFAFTAUKQIJAFUPNGZGABWEDEAERRQBHDFRFYS", "UGXWSNSXNKTSGMULRHOMTNGCTTGMIOGIFQHXIZPMUXOSUEEG", "KHLMERVBANHEQRSWSXPGVIHKPTDECQZDNLDHUCCOKRZXJFXT", "JDNPEIVRHIVNAJQTWCQAKAGJBPOQNYCLYDCSOWJMIPBDZHZK", "NGQNTRHFMZQZTKIKYKIAVYLLLRSCCBAXXBXMNEUWGSKVBMCE", "LQCKUNFAZKZHIGEDAAUAKNYDZJVTXOCVXCKICXDDQIHYFAOH", "UABFOGPEPNJKBJEOGTUAGCQJIVRBPVVVWBVDCVXFCSWNKUQR", "DEWDUVLZLQAMSSVKQSCZDQWDBMOKMISTQANPXERKBJAUOHZJ", "KHBPUDLXTNNWGGMWCOVNZINCUNAWIULUUZBZPFOQPKHZQLSO", "GOOPWNDHPOLLJHXYPKPLEVTJMFRNSLHJLKARYJRLBMCXELOQ"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 33138;
    if(result == expected) {
        cout << "Test Case 6: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 6: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test7() {
    vector<string> input = {"NPCWWSQRWKLLPI", "IKROSKMLQKXNTE", "YBIMWXZKVDSMYI", "SWICUMPCNSZQKL", "AVCVSVLEIIXWCF", "ZTFZLBPUWYSJOD", "GMYXDECMZHMINI", "AZYFXWJCZEDVEQ", "QIEIEZQUQNPMJY", "MNFWKHFYYPKAYN", "SAPJLSHLVBUIRU", "RHEJBVWBHRIVQD", "BMBUEDAHYYFTAH", "PZAAFQQADCLUIJ", "LITALOIZEJKACL", "PUCVXRHDURSWKL", "OLIYXLXOVYPDPI", "HPOJVNDSHZNUPU", "WNOXPNYZAPKEWK", "BTBFHXXEHWCHTC", "VHYDIIINKPDEXR", "DKXQLCTFWDNWJO", "PVZNIIQYJFANBJ", "DYVKBUMCZYFCQW", "CFHZPSRHOIYVAA", "GUVJNVNALIMJXN", "XELBKJLQPLINXJ", "PFYCXPSGQOZYAU", "XPGROMGIEQXMXE", "ZXFKDGQXJRRFCB", "NASVMJRMYATREN", "CTFMPSZMJYTHAI", "RSAYRUCPFLTQZQ", "QJVBYBKFFXKOKJ", "TOXWSHQAZAUOFH", "HUYUVVRKZMUWWS"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 18584;
    if(result == expected) {
        cout << "Test Case 7: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 7: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test8() {
    vector<string> input = {"NKUASPYVEJN", "SMMULCJZSDI", "LPXHFYEBFUP", "HZYAMMAAIYB", "RUYFZJXVCGG", "PJNWQZSSWOZ", "PKXRYADWOUE", "BUTUSFKAFXS", "AAYWFHETKJX", "PISTJNJYVOW", "OHBPJNLYRZP", "WUNATDMZUYK", "LMGCJJPBZSU", "RMHFCQYCEOR", "FWGBOUQXREQ", "BJKXVWODMJY", "AWZJMTKSXME", "ECCWRMVLTCZ", "JAZJDRSVOOA", "TBOQZRZYSKX", "AWGULKPSMUU", "LPAKYREONQU", "JTUMQAVNUUW", "UZODRHWWRBY", "VDWQIMTWPJY", "BENPEVDIGHN", "ICJXTFALTZW", "IWADUZKCUQY", "TPQGFVCFKVN", "SNPSTXWLZPF", "HSDPIUAGBBY", "CYWHSUBUSVM", "OQWVJAXHZPU", "DLSUTHKAYCO", "PUMGYVMVGBW", "DYUZFGGDVPM", "YKMMTXYHHVL", "ABNHOPGEYVD", "TPPRPTINMTM", "MANXRQJUZGT", "SEFHUGISFOQ", "XKCTSLGZBCA", "CREQIOOXFOP", "ITSHPBSZVAJ", "ZWJJOBWJLAI", "ILRZLILNCTW", "MQYWWYOCNDE", "YFBWHREUPMV", "QUUTFXIYHYB"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 22819;
    if(result == expected) {
        cout << "Test Case 8: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 8: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test9() {
    vector<string> input = {"FACWKUTGWSZUWZPWDSJQSWXSOBMNTQERERADMFXJU", "SQIOIXFXDWQJJPTKPKOQUUAZBINGHZLERYTRUVTWX", "IKYSUXNDDADODEUXGIHTOALTJLZSRNRDDBFDSFEBS", "CQVCQOIRHTOYKYOGZTRHUZJEBTMLTOCUPFWAXURSB", "JIOKEWQQGOHGZBJGSBKARTAXLDTIWUDDVBXUIPEVG", "EWOHRHNXFKCHCNCWKADHQIWGWGIXGGHAXNGUNLFXN", "RJKLWOHEPANXLRFIMCXLLVNQCQDJEJJTIGZTVVSBH", "USYRXOSWYUPGAPAHBDVNRAXAIMAAJKUTCBEZIYSPD", "DCYRUXBQRLMCIJVTGWIZWGTTDNWLJIFHKNWSDAOUS", "PRKXLLUTMNJQUOGOZOOVZJUSITLHYEOMCVGWHMUFX", "TSZUWCYYMQRXWDIKMSBIZPFOAGLSGAMHKTUOMZYBP", "XRWAPZKZUVJFWSLTNFPPHBUYDYJSYXBPATZYIOWKZ", "QOEMRCOHXJAKPHQTWTWQIGTHVXRNHWRBDLGQSBQYE", "SGBKPPRDFWBXRMKREXXURYIDBIWBVZBGTPWFCEZSY", "DMOEWBNZMJOYTLFHJRHPOBRDEXOCIEYYDOCCQEMXR", "DWBCIMPFHLLTSVRUZWARNGHLWOUCDJCHVONYEXZUS"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 26489;
    if(result == expected) {
        cout << "Test Case 9: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 9: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test10() {
    vector<string> input = {"GDZBPWEKKYYYSKLWSKWUJYHUTWNBFZQHW", "AMWMBBNPAAFQPRFOHRVSQFLPPEUQRQFZC", "FXEJNVUCQGZKDMIBIOGTMKGWJYZTKAVTD", "TIJQZWZLAGUFCIEVDYUILQLMFZOILKAQI", "YHWEAOOCIIVYABVRTUGDPUZGPFYDMSEEY", "EEICWJMJFQSKPVBVQQTPWHINXHHRZHMDE", "YWCGWPEGIKEMYUEIHOEQMYFZIWBVUWMDL", "QDCHRLKIDOLOFLBMOFRMSTSABAIEYGLID", "IISJULSYXUMRUSICSCMRHUYRZMJJWERVG", "OBNJVNFFFGNIQBZRNPVQSAGYYSESKXZKG", "NGIVYCZWTRPNWVHSRODSRYUNBIKVELZIX", "KEAEEKUYZGTVMIXMYROCBAGHJAPCUCXOY", "PXEPSGBMHTHAYBBQCDRPYMANYKMAXGFXF"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 14788;
    if(result == expected) {
        cout << "Test Case 10: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 10: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test11() {
    vector<string> input = {"ES", "WU", "DD", "WC", "PP", "OM", "OU", "VW", "DT", "JL", "YN", "VM", "WI", "YI", "OA", "YE", "ZV", "HA", "RG", "BO", "WA", "YM", "NJ", "GJ", "WA", "RU", "HN", "ZZ", "AR", "SQ", "MS", "DE", "AA", "XN", "UY", "NF", "OY", "IY"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 2458;
    if(result == expected) {
        cout << "Test Case 11: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 11: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test12() {
    vector<string> input = {"JDDNL", "LIHHE", "DZTWL", "OFSHK", "FCNHU", "GEQMY", "JWUFW", "GMYFN", "RHJYC", "SABXN", "WQOWV", "OQZCU"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 1193;
    if(result == expected) {
        cout << "Test Case 12: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 12: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test13() {
    vector<string> input = {"EZGHNPPQNDVAXWRFTOEARXJWNQCKXWHA", "CCNWETJEXLWNCEUDOKLYVALXNVOIXKJD", "VZEPZUDUUNCGKQDVCVMECVLNDXINXQPK", "KFFRRFDZMWETBOKFXTAZQTSMPHIIJRDG", "SOKVLPWPIHNUNNWAGFGMYULEIVZFPLMB", "FVZECWZWIFUPNAUHLSXDGMXRPFQYIGOI", "XDZOKBABWUTQHOCFQWEXSKZLKJWONLAX", "KXEGQKTXSWMIWAKBNOMFPTEDQLHFMHCU", "RXYNQOOWKRPHVEMNHYSLTEKRMMJMCGIZ", "LRUVSZBAOZXNGNJEHBOSGZONCGZTJKQO", "JXMBCVGUVSGETHNEGNGPQKXLHDODGAWB", "CPKBOXLLWIPIEVOKKKKLXIAYCLWESPGF", "VSZNHVYEPXLBYDPRIPFSECTXSBFLBAMV", "ZCOXXRNEQGHXHPVFMCWSHQRGNAJMIBPT", "EMIUZQNFGHPJEFDMSXFLWWLGOUGGJYQN", "JUSJPZBGHRXWXRFCZWQUOGVQGGOJPHZT", "LVXKBKILJUBSTDSGRWGAOUSEDNSZNLNE", "SBOAHKJHNUWQUXYBSNIIFZITDMDTFTOU", "DTXGYEADWEBGFPKJFNXXDKXCWAUZBIGE", "HEBKDLEWTFFYRIWVLYSWMDMKLCTFWYKB", "BJLXIWATYADBZHQESIJYHRASCNIWEGAK", "BZRJJKZVBQPCBTEOUATZHDMVQLCGUGUK", "VEPVWELFOMANZTROOESYYPUJPRPWPVEY", "ADMMYJCWOZSMRVBZRKXAORHCARZTOVGD", "RQSDVLILFJAXIHLHVGAAALBMIJVKBHMI", "DTJOHWXSFCFXKBLYZNDFFOANKSPNNQVE", "XDMPTPXSMXAMXWAIZAMZGORWAUALDQEZ", "WGCXZEXSKUZDRLKSJMFGPOXCOBSMVDBM", "SBCLAZOZURSEEBNLLXQTODXHWBHUSJHO", "UQQVFUZERSJBINGOSXSRDJPWHXPFQIIO", "UNMLPKCNYOSXTAKLHMMTWHHREMBPWNOM", "HYDAPSMUKFCKCLPYYZHGFLHIPSMHESXV"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 44463;
    if(result == expected) {
        cout << "Test Case 13: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 13: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test14() {
    vector<string> input = {"KNTXYCYRUYYDPPZGRKV", "WDTBDAUFLUGHMEZWBIB", "HIRXKNRCQEWHOAVYTNM", "UBBEYUBMAMTFKMEZIPF", "OCULNLGKLFABOKYUYVW", "OWHKEIOFPKUYKIIQJPG", "BYXJTNWQGKRIMNRHMHW", "PSGQJTHQOVDLIYBCIPW", "QABLHEUMDHYKFNSBQDI", "ZILTMHBKPDYYBEWMVKN", "EDDVNWXQVYTVAMADHAV", "RKJBEFZDFMJNMILRDGC", "UFVCTLUCJGKQHIRTLGT", "RLJAQWPWOLYGUOPUECP", "RXBGLIJQGJPGOEZUHLA", "TWKJOVLFGQIPVWQKUHX", "VDCOXDKVFYHYGMZVWBV", "CIGXPGAWRETCRCKDIHQ", "JUGMQOVCNZCZKKZBVPJ", "NXJPYAJDCOKCPKXVXPU", "QNBXLBPRHIOKWCPRKNI", "GRLETFQENGBILBCWJGE", "SQEHQTXIXVQPTUOXJXG", "VIBOLQADTHYBTQYDAVJ", "TEGOETBGLBVFGYVGZZM", "LWJMJRKGJQGDSVXBHWH", "XTTVZPJSNFSAIAYLIAU", "JOXJHCTDFHSSJWHRTKI", "BIFDWQEPPWTAVARICGG", "GSJMQJMVKUWMCIJOWUV", "JYRGXBWUDZMKXCSEVZA", "KNWPNQPHUVGITDMBGJV", "BWQQJZEYFMTEEZJNKMI", "XCJCBSCWHIALRZAVYCD", "HEVMKREPPQPMQLWCOUO", "XHCPJBKQOLSJABAECST", "LKOGASAEAFLHYNCYQTR", "IISQWBLRZSLMNLMIAOA", "HXXDIUZXQTGRJOZAQFL", "GTLXUZKONKBBTUXPWDH", "OWBGAILVVJOYSQOONPJ", "NKDAHRKYTAKQAHCPDAO", "BCWURWMCLOFYTNHPHTZ", "GBODXVEPZEOZVFSGXLL", "ZZXXNCMUCHWMXDFFOIH", "AMWAXUUYTJLPMZCGFTJ", "KPBAUHMVLEMDSDAPYNA"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 39475;
    if(result == expected) {
        cout << "Test Case 14: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 14: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test15() {
    vector<string> input = {"RLAMQMWCXJFMRFYPDAHLCORAXICNZTAOBHDRSHHWOV", "RZCXLLOQLBEKZHKYMPPXBCVKPZQWNMFCTMJIQAKSAM", "LAZHHDJICJYRKDVDDTNJZZOGNVLDRBTKHSSAFUAVKW", "KMMJZWJSCXDIGZAWXWVVVKPBZRGGNXZQYCTHTSBUYR", "BUKVFURXJCMXNICXROLGESUTBGROMXGNSMQLPKTFHL", "CYCBAWBZEOBFLGRGVHIGJIIFNJEBNRHYBPWQQGOSJH", "BYFQYLMMDRQMHWOXVVYIXEMIOUJYJWUDMLFUCTDSNI", "TEIURVGCGSVURWLKZHNQEPTYIMLFYTCTCJUWRSYIMI", "YCGYOPSJXVLSBVWLMXEGNWNVLOIHRARNXZBXJCNTQP", "IAMFVYTTZTNPFEIDFCVWAPRCTXPOPKKHYCZWFKLHLL", "QLYPWLGPIMJFXGNRLXLRMXXYZIVNTMYYVMPOIRHZRZ", "DUMAURXSRXPJMTYIVGWGRPMPSXLJVAIAEMRTQEJCNX", "EGZCIIHKYXIMSTNYHZIKDDAEKRBWMYIZAYUDXNDJQZ", "INVXDEOIJWFDNZKIPMKAHXZPZFXTIZKDZTAUBVUKMI", "AXNNJELWYOUNAYUQBEDUSQBDMFSEDOTGQLYDNOLDKF", "MFLPBRGSWMSSPEOKQOGYCIIBXQAXQHIAYYOKVAUYRS", "YOZFHTLBMVOOKWJVLATWSTMIGMPEXGTVRBDTEUKCBS", "ZDDRYALWHYFLHYFSEHKGTHZKEAAHFQDJSGHTRXUJSJ", "ZFREBMOHNJIZMKEVLUSKHBXKLJPPKSRGKMSYARJCFR", "DCDICUFHHJYGSOZBYYAOXUGAYXMVYGODWYJAIPWCIL", "QNZFCMFGWYXBATRWJSQQKYRCLCYQBCTSULCYBLYWNY", "JLQKALAXDOIAVCVMRXLFCOMECYVCBPFBJDGTSVZZID", "WDPXJFZCMBSDQWZZUNMRJLEPJRUEUMGQVWJBDPFXWV", "EGMSIRXJRQBSEZJCUSVPIODZCTXGFSVRYJGVGVAAXY", "HSYXUJYQRUUMRDUJPVDNFWLVXRHCJPHGAVQJPSUWVU", "LJKSPBISLXZUCKKVAAHUKQRHXFAJDFCTRGYAVXGEHK", "AQZBCNNZNIEEWWNDABVUAYSZFPHYENYIBTGYLZFZKD", "OTHURDZBMQXDBDGTCUWQRIAALTTSAYHOEGDXMRNBSQ", "KWCOOSKDDXUTLOHDLCTXQVNUIAMTLOCTHOITKMQYTB", "UXFQLNNEOAUYZJKSQSNMHDQZMSRKTLYRDSRYEFAUAD", "NLQRHCNKSVHEVYXZQRBSUNXKSYBMDABJJXRDTCSWFY", "YAHILYCIYKILWZKQNEFRKARHUGTSNZPTAZEHIMCFDP", "IJTFPLBQGDCXNUAHDWSLCFYTKVMPINADWPUMDLAMLN", "MOYSSYOFZZKKLGBGWOEKFXXJPNWVMYGZFBSYVOWECX", "FGWGSLKGYTRSZPDRINPMKKPXYGMLLSTXSDEUIXUPDJ", "NGKZZDIDYNIAJGJDOJXNJUTJYJHHVMJLTDQDYNDIDK", "YVGFKTYLCJIAMWSUPDVUCBQMVJVXNYASHRJRVHOGJY", "IAGKOVOVNPXCSQOGNVMZQUZZJEQLBDZMEZRYYNJUSW", "ZKXBDSCPRKVMKPFYBCMSUHPWFARPGAVEPDWPVKSBUI", "UFMUWQUJJXIQJPLRKXUTGSIMSYKEAJMNFEMUOSSVVV", "WDYNGNCRHKCSAKWFAVMBABHXGDZLPDIEAWVFUDVFSA", "DYIUECJFNNCGHBOTCGCQEWIFTOXLYTPKBLJZGYZMEN", "OYFMWXSYFMTUKTSSRQKTLDZQPGFFSQUEATUGAQXKVT", "RZYKKWMIEYCJFTFQOITJBXBZPMRIDQJCGWITYWVRHK"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 101205;
    if(result == expected) {
        cout << "Test Case 15: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 15: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test16() {
    vector<string> input = {"BBGI", "FJQX", "LXBK", "NAKN", "AVZM", "LWHW", "SFAC", "VEQR", "HAOU", "ZPPO", "OTIM", "OGPA", "ZWYC", "QIYD", "NHQB", "CNRN", "KDOM", "GQBC", "CHDY", "RRFI", "PYYP", "AKXK", "FVIC", "LDTB", "PHOT", "TIRN", "URJH", "AGBC", "VOEU", "EQTJ", "ZTCG", "AGQA", "MHCY", "RTGD", "TTGW", "JFBE"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 4361;
    if(result == expected) {
        cout << "Test Case 16: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 16: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test17() {
    vector<string> input = {"EFRIVHRBPKQVVSMTQVIEDZZTFYWBZL", "TTJFGLGZSDSKMMBBJZNDKUXCFCJHYW", "ILZLIEXVXUODNVIESHTMENCIAMULUT", "NUMULIXBOGEBMYJNOKOJIKNSGYCBHE", "KHLVFAEXADTHKYHVFCERWHYGPSPLBD", "TYWBGWCWXPDYQZCDTZHREBPZDDRTOW", "ZPPOYZYXPILRSQHXACTXZBBDCBXYFU", "YARBRCYINQHPRBELFSQMDCYBSEPIOW", "LXJQXROGKSAEAQLLTLAJVUQAJWLJNZ", "BIARHHTLBYEIPBTIHXZLPJZFVPUFHR", "QNOXZPZFEXCFQGEQLZMLELFMBYWHXB", "SPOPYSWFETUROIGHUIBUPYFADHEMXE", "NEGKPLAYDBIHATWEFVCUGRYHPCJSFF", "DVERTLSZNPAEZTNOHSKAXOQKLXYXQX", "VNVLPRNVXXWSGQJTOPUCXJGMDATJGJ", "QESVAPQODIONPJJMILCIFQDDQISJQJ", "XKRMAAVQKEANLXPODVLKPAJCXQGKBY", "RUSXFYACRZOKTGOKFUFHLASBSMGDZP", "CYVHDQBRGCGDADDCNNTGANUSNSCVSM", "DTASWWYKQWMGBJWAAMCQEYCEPTSPVF", "TQTBIIOTYTIDJLBIGDAPVKELIBVGJY", "YITUXYFLFTDMJEDUNZDHLAGDHOVJNJ", "NUTVTKSZHFUNWYYKLQGBLAZFCQMMSN", "QQOMQNSVWHOZSGPAEFSPZILOXNVBVY", "JUUXIQEFGSGWJOKSOUXHPEBLKCDDID", "NZWTKAXXGCBICOYHWHUFIBPCLZHOES", "DUANQIFGFNTOFITYDZMNQFASCQQNGE", "MXNQRNMQTQLQKXFPSSBLESCVGCOJLH", "NUDGBEJKPVIUYFOKMSUAMVSWSVLGCX", "ITMXNINXKIEDDTJDUUGVNNDVKWRIXU", "XILVDNLEUTAGZKQFYFGVMDVCIJXYDX"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 38848;
    if(result == expected) {
        cout << "Test Case 17: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 17: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test18() {
    vector<string> input = {"PGZWSUOZDXOVIOHBBCPEABDHZHFGQXZGCXFHLBUUUSIUG", "PGZDSVMHAKWRVGZASHPIONISJGXUYRKAQSLSPUTXKQLZK", "HHPVNAWFDZOTHCVFCLQKCAVXRAPVPPJUXYENXAVKIFFJU", "HQVRAZSWROFTDRITCUMZUXMHNCPVNUHWPQNABWMIOVBIW", "KKNODDEZWXZEZHORUZOEKAAVMVUZOFJLQQNZKSNUHOCYQ", "XKPEVWXBDFPDKXOASPWBCPYLGEHVRAAHRPRZWHXFVEXDB", "JSJRRBGRLVXMQAZEHTHRWJMBEKUYKRASUKNUBVGWBHJGA", "UEHICPJLSYJRAPNDXXMWBGRGGHOBDRLTWMECHQDPMGMUY", "KIPIJBPTNVNJTLJFPBIMGXEKCKEIKPRUILQQCKERALMWM", "HGVWOMPMZARDMSJNMGJFKGPGMRXCBJJIPLDEOPNQMKTAJ", "IVTUZWLHTTZOJIVOCUSUSZRMDKUCIGSAMDWOYIBFUEWKV", "THOAVUDJWPWRNWZWQWOGBTFGBYDCMBDZNGYOXRHJHCOYX", "GBLGZHSEGKOVKSZDIYODXOHIVCMFOJDJOOOTACPULNVUX", "RLDRENGBGJOYJRWVYOSSRHOZEFTXCNAEDKQTXKVKIUWWB", "ZUZWOZEQLUWZQSGTVZIKBZBKWPDVOFUZFYEYMHTASHBGC", "SGFIPPYTHYCPWUPJIYCIMVVERADKZOMSURQSKYQYRFRNI", "KADDCVWJAZKJTWXLXRIDWDAUEEJFPLEKROMIUAPICOACZ", "QZUZCSDGQSTFVNZVYHQUDLEJLKIQXSWSRVRIOAZHZOTPL", "MJWZRJABQTPOUYPDPURMRPPUJMODEWGQVOFOKUAXMFLHW", "DRZSJHRPSHBWUBXHHOFVLPIFABVTLYLLIAWAUDXJINCRZ", "YQYTRAZMBHDTQGLYPYURAGHTMEWGQKOGLIEQWVUGYNGSI", "MRWSRXMRFRHXIOBGKKVRWUYNPQWNNBVVVCLHHXETLCZRS", "HOFHFWMVLXBVCTMKRJJVKRZOUBPDJKUIDUPXHWQYYKFOI", "RANPKHWCAGQHVYLBSPAWZRWRVXOVZPZZHAPLLWYQPYXHZ", "FAZTUZJAQYTHGOHZJAYHHMHMJPOPDWZOSBTYDMLUGWDGZ", "HAYMMUPNVWGKIDVXHUFMCSBDXRJRCZINCWFTBBDAPINPC", "GOSREMAPWPGAYTXZHHHOBWMCEGBYAWIBEUYAZHPJMXAKS", "KBHPUVUIWFYIIBKUUYTEKOPTROQNGWJZTCTXKZXTLUJRL", "OFEQWCVXCKOZBXNJQSBBAAWVVYHTOGZMAYGINGYGAHTWV", "MSXXFDMSVEIIXDRZQCMZJHXVEMACXKCMYMPZALLUMGOMA", "TCLYFDOQBMOUCRFNPAVDUIZKJEYHDNUKTJBKVQZSFPODH", "HJHDYNCDPXUFNHSSTUVLQHTMRVVUOIDOHVPQBBORCMANC", "GLBWZSFAEIISXMGBXCJRUUMDUKPUVURQGUEJVPKTGCCSW", "POJZYEIZFNJMSOXMOPKGJWLJQMJQJLRTUPKCMKQUFPEUQ", "TQTJRGWYXJPIEPBJKXBDQEMUWKIUORIWZNKDFPOTOYMTG", "ATDAHXXONPGAXDDOCTGUMGJURZTZHYTHLXALQJVQBOKEF", "TQGPDQLDIPBHUHORMNPCVVBVHKELDECYWCUFPVLZEPWNR", "FPXMNTLIUBPCLZSORSZKBNFKDVHLQHWLSEUILBZBLFWBF", "LCKTGSEQKPVXMWSVJONANXKMJJIVQKTFLALBNHOLGWUIR", "KKBUDSYAKODFWHAHORXWDFMHJKQQZKLBRGWWHERMMPTDB", "ZVGIDBIXNNKUNNRTXURLVUVYOGKUFTDOCTORQUUHFDMVW", "GGFTTHFHWIONPRDGVSINFDAASBSMUMPOOQNDJBONGFVLM", "QMVTRYQBDDMDUFXSANSGZYNRJKJLOILHAECVTJGHFAFWM", "AILLGTKHBQWZVFHXULFONDJYUMXLMUDDDMROWYDVKOYGW", "VTTFTPPKAPLRIJHLLMKIFFCDAQGCFNZULLITWSZKFPSIS", "VRWWIDKTFIEHEOYXBYNZSQFERFXDWTLVZQTEPVQIXRHVU"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 118471;
    if(result == expected) {
        cout << "Test Case 18: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 18: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test19() {
    vector<string> input = {"HAHFQBSJKKYRFMSZPCALWNPJBEWDBTERNQUH"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 1028;
    if(result == expected) {
        cout << "Test Case 19: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 19: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test20() {
    vector<string> input = {"CHBIONSLVJMAK", "GPWKCXUGZIPNH", "RRKQVNPSAUFKK", "EHXOYHDODFSDM", "FMCJCGJNEWUFL", "EODVPYJQHTVUV", "OMXTZQEKBXMWQ", "QIDQIHURSSDYB", "MTHQDFGGZJFAK", "TRUWLEXQCFUYV", "ILARXZDXPLUSJ", "KRBLWMHZBSBRX", "AYGIBFKKVIVBT", "IHUPDTTNCOBVW", "LKGSMNKZQLCHM", "THBPFREMRIWVO", "VTYUIPIWQMNQW", "CDSTZEVYBYPCC", "EHKZGOQDSFQTF", "EXBKSWZAGFDNR", "NNPQQIEJUXZXW", "EPQHEOZROXIZA", "FKDBUQTSRXSCE", "QKFGRPVIRGAZV", "QNPSTYOYOJIHP", "ZFRPHVMKPFOYJ", "DVWLGVPDSUTIM", "BGBUNRPDDFJLZ", "BIJNQHWIQUVCU", "WGVWRRDBVUBWD", "HSVKSEQQXDKGS", "CVYWXACOKCLEG", "WTJDHSVOEQRKT", "OKXGEUASZUUTH", "VJENUKLABGNBZ", "JSZCDQCRUBTSO", "RBXYSDAIYBMPW", "ZFMUFRNJCAYEK"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 18351;
    if(result == expected) {
        cout << "Test Case 20: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 20: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test21() {
    vector<string> input = {"QEHOXKSZICCBLD", "JMWRGVZZXKDGLQ", "PJYIRBVBATQXAF", "IOSDOASENXGFYX", "JAHWWKDWGRGYKA"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 1435;
    if(result == expected) {
        cout << "Test Case 21: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 21: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test22() {
    vector<string> input = {"CEAANARMEN", "IVJVYGXRXR", "DPBJJMXDBC", "CIKMIFOGIU", "UXXJCKZCVH", "LSMUZVYQEQ", "PYSMWYPBUI", "XYIVDKXYAU", "DTPEVJERYD", "UHTZXLQRMM", "XKPTTUCNRT", "JBYGUNGAWJ"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 2777;
    if(result == expected) {
        cout << "Test Case 22: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 22: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test23() {
    vector<string> input = {"ZKOTBSBTVQMKUZXBFZFTFTRUGCMOAAJLGBMTGEKXNBTTRLB", "WEWKAQUTFUBLOQBLGCXIMSOERQIGKVPJQTLXJOTLHHRORAQ", "FZBHLXSNOJSAFANHKNFYGNGETEZTQNQULQELLBLUBBRQNEW", "SNLMHUGXOZXPLRTZEAZNDWTIPPVMEVINRXYHMGWMHCLXBHG", "SYTFCJGZKJMHKKUPIGCROVJZYDSVONXXEXPAVKNZGSCLKCW", "XMGTXIPVLLOBJYPYCZTATZDKCWPKMUUCMWNUIMEJRBVLQUT", "GBDYPUQNGLXSAICKBOLYLGEWGCSVOYHCXYXGZJTMDCHHLYI", "PMEIDZXBPXXEORWFSBOPHXNCWCQUZHGGVQMPDHWGMXZNQKJ", "UXIYANRGNRTJDZHABHJCUJACDQBFTAERZCGTMCVYSTAOHRZ", "FIKZVIYUYRMWYPGUYZUYEATZEALDKVADPEFXPIDRKTCFTQQ", "FNDSBURUWQKTBHTVYHQNYMWFBXBXFJWXRLVJEEKPXHXKYQN", "SYZGTLJZHMXWMMABZZVVRCEYETXDRWOGPYBDIENMTDBLWMU", "SAEZTBTWUCESIZCCGMCGXKXKPQERJWEMITENZOAMYQDJDXC", "NRHKJJPSAENOBGTANOCZQNJBXJBKFDRIYPCNFWCFHWHCQVF", "AFZZCXIOTZBIVPMMUIIPNALCHSSSQUBLJHYGWAAAMODYQUO", "IIHTUHVUFRFBQPHPPVOPEMCITAHIFGSHDTVEVVJVPPNLYWW", "PJWZJZXZKDVGQJWKGAJSHJAZEVLKBNNBPCRUPOKWYZPBIJX", "FMRZHNWPZHFAKFLKHTRTDHRZHTGWFZWCSCKRXHKFDJRWVGO", "LGHFKTJCEDQIAPBBPMQZFXZMBKWITVKFMHGNVXXLFEFQOGO", "JEMFYQNYJOZGQUXIDGNMZCQXTISJCONYWDLCEAONLEQRXIN", "PARTTYSICPIGSKNGGHWNSTNPTXQBKQHCLPKSJZHJAOIZIZB", "MQYKIQWOJBSPWXPZCUUMYRKIFKOBWXQMZZMLDWCPIFUBLVV", "SOSKLHHOPPYWWMXEZRYBCGOESOQNMGRZCSYQPHBQHWXBOWE", "NQQZQYXSKUUWGYJZWHYOIKEUEYBLLDQQTCTVVWXLARXHNPH", "WNQVFAJVQVGNZLWKLQCNJKSFEIWLDAKXOZNUIPCIKFEKRQO", "JCMSDFVVDGFEMVDYUHYLQSXHCNAKCLQEICYGTGIVCVBYUGO", "VSMCMLHZQJQLDWANUSTIDAVVZRYPDGVKAJFFTXIZGPGYVYI", "KKBZAEWPIJSXJZHEFLNTCJONCWIUZMTCDNOXHBRIUQVTFUX", "OLFBPXMQUTALSKYKUMMDEFAMEQWCEYARJGOVMXUVWIQGBPS", "IPMOISWANAFRASMJFVJJCWCVPNRRGAIULZUVXXVPAHZTTWG", "QUAFZSPPGNUHHVCRVGFVMKUYTJUEFOWKGAZOBLTSNBNKYNG"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 73885;
    if(result == expected) {
        cout << "Test Case 23: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 23: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test24() {
    vector<string> input = {"KDNPDPFLGXTULMXMFOYRHWSNIGRBCH", "QQJNUVDMCRIBNTFANPQRVZOIQDLGVS", "LRFDOGFLUPYOZLIKPUXNZVSUNXHBVU"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 2575;
    if(result == expected) {
        cout << "Test Case 24: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 24: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test25() {
    vector<string> input = {"BLVEJZOSGMSCKUZSWQINPXOMZVVV", "ARIGNKEBWBCMNHAQVSXDIUMLDYMI", "SVAJJDWYKRWCJRXANXFYDBKWIWHU", "IUVUCPMKLXYWGJCLNBFALTAMSSYB", "RKMHJDBLIJLMJKTQBNQEOINZNDCV", "IKVPUHZWVQORPYHYNKKDSIZYSGKV", "UVDMPVDBPRPNVQCZOTCIKUKLYQRM", "AHBPHTBSNHSONZGRGSUNHELAWRKI", "HPAOGEQPLBMYEISLMJFSPTKQALQC", "NRDGPSBCEGHUVJJDWLBTPGOUPFRA", "SIXILITUIBPSCRCGUKEOKPMFTEXV", "NOCQJICTBGGCUPUGOHJCXQWUQKNG", "PTTXJDTLVDMYJWKOSBOVHAIMDKNU", "HYBNSHJQSYQXYIXHHUNXFXTXLRVZ", "RDBSYPRKCEQEGEACPCBTMNVLRKET", "HPLDQWEGMKXAYSRBGMDRMNEIBEZQ", "EEBBOXWFIDMXKHBHLIXTSUDQRBSU", "ZMXSFZQAWWHLSWEDYWTJETJUYHJT", "UZSIKEOVFPCGPNLFUTPRUIKEJWGB", "RUQRDMWWFLJHZAUKRKMRVSHOQSJM", "VGRLWBBZIQIEFYSATAQTBZLPGRFX", "PFTWSMRIGPYWZALRCRSJWTRFXQSJ", "DRDECXBDUIQCYTYQWEWIAIBBRVDI", "TRVMXBMRVWPCZLPXHWQSYRANBYMO", "PKMVYWTWDBEHDYQGXFHSXUAVECMP", "LODNGVVHMTWZTOZMOQEAAUYQDPPO", "BPALLJKPKERAZAUQIBZMONQFSLTL", "PQOXUKQGACVHLGTDVBCNXDEURFJN", "UDJJDVDIJYWSIJNLTYGGVVKQTRNX", "SRMNEKNDWBJXJSKLTSLRVMDVSBSG", "PZFILLCSVNIHMWCUMXBKBNKAZJXI", "ILXVXPBUGPPZDOKSBQAXRZQVVIVB", "CDKHXPPNQOHPGIKFDKLKSUEYJOLM"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 38885;
    if(result == expected) {
        cout << "Test Case 25: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 25: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test26() {
    vector<string> input = {"EFVSCRHOHOCBMRQMQFGDYOWC", "TLBOXUHVMEVWKRZCNGCEUEDU", "NTNOJVMRXLYRHNLXXSIUHPXC", "OXIWKAYPNBLDJXVVYYDYXUPD", "XQAHKZTDFHBGJEQUEIQYFHDI", "WASTLYLKMBEUZAMJVDXFJMNA"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 3825;
    if(result == expected) {
        cout << "Test Case 26: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 26: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test27() {
    vector<string> input = {"NFTIYAABLXNAIYPCWYNHAQRYEBEQGBPWIPKNJIYYLZOK", "JIZIQGCOFVKDAQYJNPJCCNKAPOSEDDYPXUEZHCQEEOCG", "HPAZFCUKKQGPZVHIUXFIETSGBYVFRZCRJWWBQYJQXURJ", "XUGTQJVAEURRUURGXYJKGOKJCZQRJBQKKJRPAOYFZLLY", "PVCLOIEBAVIHTEOATBMDNQLTFDNPCSQYVOULWTVHKHWB", "NMBIXPOCLCNUSGRAZPMAWWMZIHSHVLXTPAZGZPCBHHVB", "SUFXIUFKTOILFTSRKNZYUQFPRXCIWICFDPQSVXYENANW", "VZRPINYIKNYUFZQGXFZVGIZAZPLZGGFBLNHXQMOWKANK", "YDNXESQNHFOLMISOZBUABJBWCWPROBCEZTYKNDJYSIBD", "HBHDEMBSXGUZFQYZBIZAEAPZEYPKGVXFTFXECPCUQXZY", "SYBKHGULJOYNKUXKPVZVCFULZICWMSUEHRVIXPGGUTSM", "NURUACBDBWRFUVPZRPZEGWNSFWBLTWTYSYSTPIPPTHKW", "RXRGIDIMXLVANTWDRWYSRZDLCNITZVROQQZRGYDRWKPO", "CRVGHZRBZGPMDPNAONYHFMFMKEAUQVJWHVFZAEGMFBTD", "EIFSANXDRJQJEQCUQSJJPJDRTZQQWDYJGOYLNZUWGFHH", "GRENFNVOJTXBVQQTVJEHRLNWCFGLWRUKOSKPDKKDQOFO", "DLBCWUDZCGCGASEJVBBCOTAXEFXIBGWYRHJWQWXGQHOX", "LZGRAPRNQHNCBIEZINQGFPHCTZLAPWDGLHERBVDGXNWL", "NFNDQRKVGFBCDDPQCVGRBPOMCKQEEOCWWPZPNGNXGANV", "OAJTEIOEVBXEPZYPHEEHKPFDYBMZDIVXQFEZAKJPKLWB", "GLKWKQBGNJGNMHSAUSCLXQTKKMEYNYTDNLSUXVWRSVBF", "BZUGJHMMCMYVRONZDHGUDADRKOSYCURSNRVVDVONXYXP", "PYGEWENBXRUPUIIHWACCXKZHENRDRQRLQDNRRMGOVMOP", "YBCHKZFTQUMPATWIQETSMYVRVKKGKPROIHOTHNEEBOSC", "OCZOIQAYAYLDYMXBHYGZCNWSTXOLGHNDIWRLAVBIYETP", "RQMBAGHFEYOWGAJOECYKZNFKRKLWMYQEZCDLEGSXWASB", "LDYDUBADVOEXEKNOOYXBOXOIRBZOQAEFIJBNVPYABSLP", "LZJQUVFCPFULJYNPXBHFPANAKBNRQDOXHKYOIUFNJJKY", "XJVKNUMKHNYFDVQHCAEVFGNTIHWGYSSZTCNVBLNFRINU", "NHGMZOAYJCJXINBBBFCZOQSVRTURMJLQIMNMYXQUCAWK", "ZPHJJNAOTEXJCKTWEIGVPPEMXOYIMRJZGGCYRLXJIGOQ", "URXBTUQJMCBGMARUIRYTOSDCXHHMBCMJLHVEKSKSTRDC", "UMCQYXYIIZVYSVOAOHHQUNIXYJPWEZQXHBDAZJXJSDGE", "ZKOOGBURQPHNXHDOLZFRDCSCODXERXHTZZOOURGDVHFI", "ONKUCDVZLRAZPRURHTXBDZQGNJFKDWNGJDHMANOAEQRV", "MGZSEXRJBZBLMXEISARPMDJNUEPOAJLZWTMIIVUFOSDE", "FKDEBLXDAJLZOWVONOTPVNXQBVCOEMEQOBMTNMYLQTEP", "DCIQTKAKFYBPJXJPVQTORPESORCONBELHBGZURPVHNPK"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 87771;
    if(result == expected) {
        cout << "Test Case 27: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 27: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test28() {
    vector<string> input = {"ZGSME", "RHPGN", "NINQN", "IBZFJ", "AOVSV", "FNZYU", "JQUXN", "GHNPH", "HBSMX", "DMFDH", "MMRMI", "VCJWA", "KVFVE", "YWLNK", "SKNZO", "WFEAB", "YNXUN", "OLURI", "VSWSG", "UIEXI", "ZRZOW", "BCNTA"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 2807;
    if(result == expected) {
        cout << "Test Case 28: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 28: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test29() {
    vector<string> input = {"HRZSYHVWINLXDGNRAZJXCFINLXVAL", "XZMOMJHPZMQIZVAGZPAHCQUKHSFBU", "NYOGGQASVPVAZQWWOCHDNPQGEQKMZ", "GIAOGIUVGRSAYESBQMGSWEMFZILGQ", "YYARSAMJEIDLFZAXIZETWHXLEMXZZ", "GYKQYDXYIPHXKJBFHVVHRMLAIQZUU", "XZMKBYRSMXSKCUILZQPVCMTUCSHQB", "QCZSLZSWZUFYUPRDHDFGQKUHAPFNY", "DBQXCMDBLDOPQRIHCDMMVBFCSXVBY", "PJNWBHCMUXSXAHXAZOBFXGPFDULYR", "WIFMHCPDXZMTNYQYHIAJINBFSUUDE", "GFKVCKPHUPIXXCPBPDLIPPQYSSMSS"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 11232;
    if(result == expected) {
        cout << "Test Case 29: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 29: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test30() {
    vector<string> input = {"NVEUTIYTZXUVXZPOQSLAKOGDKOJWDHSPUOXRHSKKMQ", "OIDRDIXUTSOZEPPJXVOCOFXUFUNGPAHHUBPISFRZHN", "FLGOEMIAILQXFTAKOTDJMNFMUMKGEXKIOSXQCIVQTE", "OSZYCKSYYGFZUZKUTSBOVCDMLSUMYPPOKDMNEGUMBF", "KDRBSULQDJMAVWNLRIVKVHBVZIZXPOZWRLBLSMLDAP", "CJATZXMPEZPXRTGOVASNUEQMQTUIUBFDLEDWSVENUW", "OLOLBKHOSTACFUAGOROCKGQIBOASDWANEGERGIEIEX", "KOMNRWDAAUVWVBJMBIJLCFQHPFVATBOJZLPRRPIXZD", "FWUNHPQQEZTTUDWYGEJSVVODWHJWGVWFUSKOFQGOWV", "CSIBZCFCVVKLIALEOOIPADJNRVIOFKZJYWJOYZKZUI", "TSSNVRNUGTPGECMGPJHLOMZYCOARVUPMSDLBZUXLNG", "IQGIKNYHKLSBSHWWGCCHADHVDPKLDOVQXSWXVZPVRX", "MGCHHUMMZGZFWNRERFWEEDFJLBHVWONFXNXTWWEUMB", "GLKPGWCAULTEGWHBAHZXJCJBAKSEZPZNZGYQLXUIQU", "LHVPHEYKHBJPCQDALNAEJSCEODQZRLQOMVYQYRPUTK", "GUFMSLLGZWANWEGHOAECSSELDPRQNQOESKOPCCNXAM", "MXBLIJGARIQABNHBFYAKBYYYEAVQJQBKUWBKZZEBUN", "VFIWJWPXTAXAHSVUOUVGMKOLMWAXOWFSSQLVUVYWAC", "QPHVYSRPWAXBAXSPZWDMMJHYWIUTXYDRCIYINTRXIP", "DKRJYZJWUXNYWELRGOBIUZODGUQHLULYRQJMLAHNZK", "PHCCJZIUUTERWHWCWZAVZYCHZPBQDWYZRRIREKZGGZ", "WYWSFKHUKXKUZMVXVZUCHUQQBAMGFAQTKLZMQJLZVX", "LBZOOBZJUXAEFQUDYNXQSBRWGUBWRUZGQQDVMWGDZY", "OVVIANVSPNOITHNWOLUAAUOHITTLIYFIDCVSMOPTUS", "RJHESGLPTCADYEHEFILDNSOOZVWIPEKTCYLORMOWAD", "OXFRMYCEMPINWEAPJRLUIZDEWFCXTMNRVLDQPRIKET", "ZEOBXZXLCHPXXVHJNQPZOAMUWQYAVIQPQBBERBHDTJ", "IZMCSOYXLIMPKUFSIREJWLIFFWGZWPMTJLGGVTLPSE", "VWZNECHFNOAMDPHSWNDBNAVRFAMOADEHOZNBNLDWUL", "KUWOZPDHAPMAEKXZOCZNCLTJUFVERNYXBPTOXJHCYJ", "BDITLAEQBNWGLVBXXBZBRRMTPXECRMNUXHBWRNYTJM", "LQPQDIAFPZKTNLAFEIFNEERRWGTGOTFUWFNZXXUAQE", "HCRFBQZZTCKLLJSHZYQEHGYBLXXAERLDRUOEWQMVXA", "TGGHHTSVZUBFGTIZIGPUMAVHQJXXZASTTDEPOYRQSN", "LGLRZTZTPCHNPWCTCMJGHEGJCBHUOTYZWWUKJAYZKV"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 74013;
    if(result == expected) {
        cout << "Test Case 30: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 30: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test31() {
    vector<string> input = {"UNFZPIXOWVXHJVCJPMSYGNUP", "DSDMDVHANXTSGXVXVZCUIMON", "WWXHPEHZQUDIULJXTPSBBCZV", "HNRHCEVTHMUBNNSPSJMFXDUC", "ITEICNNFWOROUICSHROWHBOF", "ILYJFUPQXSVZIUEMLRIFVCRH", "OWAJABEIZGIITYKPSECZGHQC", "OELANQDPBIAHYUTWOMHFXPQL", "TKDCDFDZUSWZCEWRGYLMGFNV", "MNOADXGRCTNTCNJPKDHEPNOW", "SMAGYTIJYSGKLIFRUMVATMNY", "KOFBHZIIUXDWBILYOGSQQDBR", "GTWTCMWAUSJBMDUMUEYRYQKB", "EBDPIVRACXIELTCNVMFLDFRC", "ZXPZFTKSAACHQFJCVACMTSMN", "XXPFCOFQKVAKJZUTXLPPUKFQ", "CRBZFGWWMCYLKJKLLWRRFWRT", "XXAZCEQICYZGBOYKGQNZBRBP", "ZBPICLDZEXWYHQDRDTVNMBFQ", "OEWZRRFVOJWVUYJQBLYFZEMX", "QHDPEKLQEHRDSEVTYSCZFLEN", "GGWMJJWQEYXSSDEEJPVWUFVH", "WOKMSCUMSPOHEQRZYDGTHGVC", "VZQALIEIDOIVMFVTDDIJAOEW", "KWDVAENBJHKJTNMSVFLLGBOB", "IJZUWANRCXFXZYTFODFBPZKM", "VJQWFOJCIWCWREHWXVFXYOUN", "OBYNDSWGOJGPCIPLCCYXMVVK", "JZHVCUVDQSOHBMFYCVYTTZNJ", "JJCNPDETJRTEACRVFPSPXGLU", "IMGISUNHQBXYCKDOZWEZGTTG", "ZVLOVNFKPJAKFJSFPCQSREOO", "SVMKLFBQNGFKCALJIEIXHVPJ", "ROHQIVWPSCJGPAQPUUGBSZWT", "FZOJFBEMVWMXAWBXRZHHTNDL", "HBBWHCDKHEVBEFCUSSNOUZMS", "NXCBMFWGCCFSCCTRQKLGGQDT", "XVZDSHMBQHPXKBRZOPKHMPXI", "CHWAPWEPQKGPUJRZFKQAZFMT", "QDROLZRYFUTZSXYNKJLMGFYP", "AYHEPYZQGWZUOUNYPGJIKWKZ", "JGOIBXKZDIJETXILFGAFBYVV", "JPBJIUEXIZYJOVXSFLBDTLJX", "XGFTCVCRARHZPMNVPKXKLZGE", "VXALKIAAQOZEPAXQJUNNVDYS"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 49725;
    if(result == expected) {
        cout << "Test Case 31: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 31: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test32() {
    vector<string> input = {"TAFRLQDEKLGSZRD", "JKEYSNCWVSZCTXE", "KOQYJJJDRARAOJJ", "REZVHADKWBHYERW", "XDFSJVKRKASMWTD", "YDTPBZEUHILKSDO", "ITOLUSUBRYUFMUD", "XAUHWJXJEVYOWJI", "EZQQLZZQUXOUNKV", "PGCQYNDIEOECYDT", "LXKVVGJXPFMAEWL", "SGQXBXEDKOLGPER", "SEAABHOTXDCCNEX", "DNMVLQKZLEOQPCR", "MSNMWKDACRDEXRX", "YLFMKUHLCYQUZQY", "CYBBJTHNOCWHRAJ", "YUDDXLTCPOTXOUX", "QBCFKCJWJPPYADW", "NVTQAHEHAILHLIZ", "SQOHOMLHIQMSEUJ", "VJWXKTCBCQSWFIU", "LDVMXCSFBXYHCEC", "IQDVIDDSYMPSLGW", "FYGLKCFKPXNYWFS", "GVKUIZHUIOMLPZG", "WYAHLIPKGAXZRJD", "THABIVRUMXMTJMG", "GGSHIBSOEEYOOSQ", "SXPPMDCPFANTXQN", "JXAHUSPKIPPHEPS", "MNUMCABCYZZBSFF", "EGBMBEGDKNAGOEE", "ZINTOGDSEOKKCTZ", "UOTHBFDYEUIFURL"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 18989;
    if(result == expected) {
        cout << "Test Case 32: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 32: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test33() {
    vector<string> input = {"HHMGQKTSGGGMNUEROIIWIGKMSVNNPKIEWOQHMN", "TNSOXWUFOZZBMQHTAAQPXHNGWCUABWJLUWMGAO", "YBRIIRMFDBZWWWGHTAFRHVGOINJUSSJECLCVXO", "PMFJLGSHLWBOUCGWYDJEOTMJYVVXCAYXDQWWHD", "YUFSYICJDQCSYJIICAIWYTTGCAHEOWRPPXVQDR", "WDAGDGVRZYOXGCSUYHGCSQNNJCWCREFAJYZTQB", "XMTUATLHAPJAGDAABNZFQRLRNSFQOOZSRJYEVC", "VUBLQVLYZFOHMJUPCRLTBGXIOBLXZBQYVLXBZN", "WTHSPFCECTRKTYUULYWSKMWUUNYUXFXHBULQIG", "HUFNOQIGZLOXFRKNZCCKPMUTFICCZACSIJYIBN", "AONDBSKAFYYNNYJADAHXTWWCIHMHTUBHBMLFAU", "YGCYUQMTENMDOXWTAJPOFYQVYLDIBIVKBLNTND", "HSZCCWJDGNNHZHZMBEZRLULSPBOBFYUQQWSDJP", "XJNZMQUNTDIBRZIIYRTYJQHWSASXDANOLGIDTB", "KINHXHOYSDDEWUSAWKGBESMCFNYWWSGSIMASLJ", "DFHIAYSVKQRTOZPHYVRGRDOOFFQTYRTZDHKEHM", "OEIGFRSPEUKDBSLPCWFCMWGWYUCUYXBUYGGQXC", "QQRTVFZIQTLCMZELREAHVMKLQWIRYWPOIELZHJ"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 27069;
    if(result == expected) {
        cout << "Test Case 33: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 33: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test34() {
    vector<string> input = {"VDQMURCNOTUEQZNO", "VSIGINKIIKVFWFCR", "QADRGVFWBQTROMSK", "GOWGENMMJTZCHCGZ", "NGBSLJOBFDIJPYFY", "WKAXVRNNIYRWFVSV", "GHICWYHIVYOEUFHW", "BNRJDCCVMVIRKNND", "GPBFTRQZABTMYSKW", "PQPNBLMUXVQMMUQD", "PDIBTCJZMMPQWEGW", "DYYKVLPWGGCHSFMD", "RHGCELKTSNKUBRIR"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 5383;
    if(result == expected) {
        cout << "Test Case 34: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 34: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test35() {
    vector<string> input = {"A"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 0;
    if(result == expected) {
        cout << "Test Case 35: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 35: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test36() {
    vector<string> input = {"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 185000;
    if(result == expected) {
        cout << "Test Case 36: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 36: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test37() {
    vector<string> input = {"ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 4290;
    if(result == expected) {
        cout << "Test Case 37: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 37: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}

int test38() {
    vector<string> input = {"CBA", "DDD"};
    ArrayHash* pObj = new ArrayHash();
    clock_t start = clock();
    int result = pObj->getHash(input);
    clock_t end = clock();
    delete pObj;
    int expected = 21;
    if(result == expected) {
        cout << "Test Case 38: Passed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 0;
    } else {
        cout << "Test Case 38: Failed! Time: " << static_cast<double>(end-start)/CLOCKS_PER_SEC << " seconds" << endl;
        return 1;
    }
}



int main(int argc, char* argv[]) {
    int passed = 0;
    int failed = 0;
    test0() == 0 ? ++passed : ++failed;
    test1() == 0 ? ++passed : ++failed;
    test2() == 0 ? ++passed : ++failed;
    test3() == 0 ? ++passed : ++failed;
    test4() == 0 ? ++passed : ++failed;
    test5() == 0 ? ++passed : ++failed;
    test6() == 0 ? ++passed : ++failed;
    test7() == 0 ? ++passed : ++failed;
    test8() == 0 ? ++passed : ++failed;
    test9() == 0 ? ++passed : ++failed;
    test10() == 0 ? ++passed : ++failed;
    test11() == 0 ? ++passed : ++failed;
    test12() == 0 ? ++passed : ++failed;
    test13() == 0 ? ++passed : ++failed;
    test14() == 0 ? ++passed : ++failed;
    test15() == 0 ? ++passed : ++failed;
    test16() == 0 ? ++passed : ++failed;
    test17() == 0 ? ++passed : ++failed;
    test18() == 0 ? ++passed : ++failed;
    test19() == 0 ? ++passed : ++failed;
    test20() == 0 ? ++passed : ++failed;
    test21() == 0 ? ++passed : ++failed;
    test22() == 0 ? ++passed : ++failed;
    test23() == 0 ? ++passed : ++failed;
    test24() == 0 ? ++passed : ++failed;
    test25() == 0 ? ++passed : ++failed;
    test26() == 0 ? ++passed : ++failed;
    test27() == 0 ? ++passed : ++failed;
    test28() == 0 ? ++passed : ++failed;
    test29() == 0 ? ++passed : ++failed;
    test30() == 0 ? ++passed : ++failed;
    test31() == 0 ? ++passed : ++failed;
    test32() == 0 ? ++passed : ++failed;
    test33() == 0 ? ++passed : ++failed;
    test34() == 0 ? ++passed : ++failed;
    test35() == 0 ? ++passed : ++failed;
    test36() == 0 ? ++passed : ++failed;
    test37() == 0 ? ++passed : ++failed;
    test38() == 0 ? ++passed : ++failed;
    cout << "Total Test Case: " << passed + failed << "; Passed: " << passed << "; Failed: " << failed << endl;
    return failed == 0 ? 0 : 1;
}

/*******************************************************************************
*    Top Submission URL: 
*    http://community.topcoder.com/stat?c=problem_solution&cr=8471704&rd=6537&pm=4503
********************************************************************************
#include <iostream>
#include <vector>
#include <string>
#define FOR(i,n) for(int i=0;i<n;i++)
#define debln(a) cout<< #a <<" : " << a << endl;
using namespace std;
 
class ArrayHash {
  public:
  int getHash(vector <string> input) {
    int res = 0;
    FOR(i,input.size()) {
      FOR(j,input[i].size()) res+=(input[i][j]-'A' + i + j);
    }
    return res;
  }
};
 
// Powered by PopsEdit

********************************************************************************
*******************************************************************************/